apiVersion: v1
kind: Service
metadata:
  name: {{ include "owlapi.fullname" . }}-admin
  labels:
    {{- include "owlapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  selector:
    {{- include "owlapi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  ports:
    - name: http
      port: {{ .Values.admin.port }}
      targetPort: http
