apiVersion: v1
kind: Service
metadata:
  name: {{ include "owlapi.fullname" . }}-backend
  labels:
    {{- include "owlapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "owlapi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.backend.grpcPort }}
      targetPort: grpc
