apiVersion: v1
kind: Secret
metadata:
  name: {{ include "owlapi.fullname" . }}
  labels:
    {{- include "owlapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "owlapi.databaseUrl" . | quote }}
  OWLAPI_JWT_SECRET: {{ .Values.backend.env.jwtSecret | quote }}
  OWLAPI_LICENSE_KEY: {{ .Values.backend.env.licenseKey | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  OWLAPI_GATEWAY_ID: {{ .Values.gateway.gatewayId | quote }}
  OWLAPI_GATEWAY_TOKEN: {{ .Values.gateway.gatewayToken | quote }}
