FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    GOPROXY=https://goproxy.cn,direct go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    GOPROXY=https://goproxy.cn,direct go mod download

CMD ["air"]
