// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RunnerMessage_Register
	//	*RunnerMessage_Heartbeat
	//	*RunnerMessage_QueryResult
	Payload       isRunnerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerMessage) Reset() {
	*x = RunnerMessage{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerMessage) ProtoMessage() {}

func (x *RunnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerMessage.ProtoReflect.Descriptor instead.
func (*RunnerMessage) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerMessage) GetPayload() isRunnerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunnerMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*RunnerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *RunnerMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*RunnerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RunnerMessage) GetQueryResult() *QueryResult {
	if x != nil {
		if x, ok := x.Payload.(*RunnerMessage_QueryResult); ok {
			return x.QueryResult
		}
	}
	return nil
}

type isRunnerMessage_Payload interface {
	isRunnerMessage_Payload()
}

type RunnerMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type RunnerMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type RunnerMessage_QueryResult struct {
	QueryResult *QueryResult `protobuf:"bytes,3,opt,name=query_result,json=queryResult,proto3,oneof"`
}

func (*RunnerMessage_Register) isRunnerMessage_Payload() {}

func (*RunnerMessage_Heartbeat) isRunnerMessage_Payload() {}

func (*RunnerMessage_QueryResult) isRunnerMessage_Payload() {}

// Runner 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeToken     string                 `protobuf:"bytes,2,opt,name=node_token,json=nodeToken,proto3" json:"node_token,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetNodeToken() string {
	if x != nil {
		return x.NodeToken
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Stats         *SystemStats           `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStats() *SystemStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type SystemStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent        float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent     float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SystemStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemStats) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *SystemStats) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

// SQL 查询结果
type QueryResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON 格式的查询结果
	RowsAffected    int64                  `protobuf:"varint,5,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryResult) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *QueryResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_HeartbeatAck
	//	*ServerMessage_ExecuteQuery
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeatAck() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerMessage) GetExecuteQuery() *ExecuteQueryRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecuteQuery); ok {
			return x.ExecuteQuery
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterResponse `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatResponse `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerMessage_ExecuteQuery struct {
	ExecuteQuery *ExecuteQueryRequest `protobuf:"bytes,3,opt,name=execute_query,json=executeQuery,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_HeartbeatAck) isServerMessage_Payload() {}

func (*ServerMessage_ExecuteQuery) isServerMessage_Payload() {}

// 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 执行 SQL 查询指令
type ExecuteQueryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DatasourceId   string                 `protobuf:"bytes,2,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Sql            string                 `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	Params         map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteQueryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteQueryRequest) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *ExecuteQueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteQueryRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteQueryRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x11owlapi.gateway.v1\"\xe6\x01\n" +
	"\rRunnerMessage\x12@\n" +
	"\bregister\x18\x01 \x01(\v2\".owlapi.gateway.v1.RegisterRequestH\x00R\bregister\x12C\n" +
	"\theartbeat\x18\x02 \x01(\v2#.owlapi.gateway.v1.HeartbeatRequestH\x00R\theartbeat\x12C\n" +
	"\fquery_result\x18\x03 \x01(\v2\x1e.owlapi.gateway.v1.QueryResultH\x00R\vqueryResultB\t\n" +
	"\apayload\"\x8b\x02\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"node_token\x18\x02 \x01(\tR\tnodeToken\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12L\n" +
	"\bmetadata\x18\x04 \x03(\v20.owlapi.gateway.v1.RegisterRequest.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x10HeartbeatRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x124\n" +
	"\x05stats\x18\x02 \x01(\v2\x1e.owlapi.gateway.v1.SystemStatsR\x05stats\"\x84\x01\n" +
	"\vSystemStats\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\"\xc1\x01\n" +
	"\vQueryResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12#\n" +
	"\rrows_affected\x18\x05 \x01(\x03R\frowsAffected\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x03R\x0fexecutionTimeMs\"\x80\x02\n" +
	"\rServerMessage\x12H\n" +
	"\fregister_ack\x18\x01 \x01(\v2#.owlapi.gateway.v1.RegisterResponseH\x00R\vregisterAck\x12K\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2$.owlapi.gateway.v1.HeartbeatResponseH\x00R\fheartbeatAck\x12M\n" +
	"\rexecute_query\x18\x03 \x01(\v2&.owlapi.gateway.v1.ExecuteQueryRequestH\x00R\fexecuteQueryB\t\n" +
	"\apayload\"a\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"4\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"\x9b\x02\n" +
	"\x13ExecuteQueryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rdatasource_id\x18\x02 \x01(\tR\fdatasourceId\x12\x10\n" +
	"\x03sql\x18\x03 \x01(\tR\x03sql\x12J\n" +
	"\x06params\x18\x04 \x03(\v22.owlapi.gateway.v1.ExecuteQueryRequest.ParamsEntryR\x06params\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012c\n" +
	"\x0eGatewayService\x12Q\n" +
	"\aConnect\x12 .owlapi.gateway.v1.RunnerMessage\x1a .owlapi.gateway.v1.ServerMessage(\x010\x01B*Z(github.com/hongjunyao/owlapi/internal/pbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gateway_proto_goTypes = []any{
	(*RunnerMessage)(nil),       // 0: owlapi.gateway.v1.RunnerMessage
	(*RegisterRequest)(nil),     // 1: owlapi.gateway.v1.RegisterRequest
	(*HeartbeatRequest)(nil),    // 2: owlapi.gateway.v1.HeartbeatRequest
	(*SystemStats)(nil),         // 3: owlapi.gateway.v1.SystemStats
	(*QueryResult)(nil),         // 4: owlapi.gateway.v1.QueryResult
	(*ServerMessage)(nil),       // 5: owlapi.gateway.v1.ServerMessage
	(*RegisterResponse)(nil),    // 6: owlapi.gateway.v1.RegisterResponse
	(*HeartbeatResponse)(nil),   // 7: owlapi.gateway.v1.HeartbeatResponse
	(*ExecuteQueryRequest)(nil), // 8: owlapi.gateway.v1.ExecuteQueryRequest
	nil,                         // 9: owlapi.gateway.v1.RegisterRequest.MetadataEntry
	nil,                         // 10: owlapi.gateway.v1.ExecuteQueryRequest.ParamsEntry
}
var file_gateway_proto_depIdxs = []int32{
	1,  // 0: owlapi.gateway.v1.RunnerMessage.register:type_name -> owlapi.gateway.v1.RegisterRequest
	2,  // 1: owlapi.gateway.v1.RunnerMessage.heartbeat:type_name -> owlapi.gateway.v1.HeartbeatRequest
	4,  // 2: owlapi.gateway.v1.RunnerMessage.query_result:type_name -> owlapi.gateway.v1.QueryResult
	9,  // 3: owlapi.gateway.v1.RegisterRequest.metadata:type_name -> owlapi.gateway.v1.RegisterRequest.MetadataEntry
	3,  // 4: owlapi.gateway.v1.HeartbeatRequest.stats:type_name -> owlapi.gateway.v1.SystemStats
	6,  // 5: owlapi.gateway.v1.ServerMessage.register_ack:type_name -> owlapi.gateway.v1.RegisterResponse
	7,  // 6: owlapi.gateway.v1.ServerMessage.heartbeat_ack:type_name -> owlapi.gateway.v1.HeartbeatResponse
	8,  // 7: owlapi.gateway.v1.ServerMessage.execute_query:type_name -> owlapi.gateway.v1.ExecuteQueryRequest
	10, // 8: owlapi.gateway.v1.ExecuteQueryRequest.params:type_name -> owlapi.gateway.v1.ExecuteQueryRequest.ParamsEntry
	0,  // 9: owlapi.gateway.v1.GatewayService.Connect:input_type -> owlapi.gateway.v1.RunnerMessage
	5,  // 10: owlapi.gateway.v1.GatewayService.Connect:output_type -> owlapi.gateway.v1.ServerMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*RunnerMessage_Register)(nil),
		(*RunnerMessage_Heartbeat)(nil),
		(*RunnerMessage_QueryResult)(nil),
	}
	file_gateway_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_HeartbeatAck)(nil),
		(*ServerMessage_ExecuteQuery)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
