/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  APIGroupListResp,
  APIGroupResp,
  CreateGroupBody,
  DeleteGroup200,
  ListGroupsParams,
  UpdateGroupBody
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListGroupsUrl = (slug: string,
    projectId: number,
    params?: ListGroupsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/groups?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/groups`
}

/**
 * @summary 获取 API 分组列表
 */
export const listGroups = async (slug: string,
    projectId: number,
    params?: ListGroupsParams, options?: RequestInit): Promise<APIGroupListResp> => {

  return customFetch<APIGroupListResp>(getListGroupsUrl(slug,projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListGroupsQueryKey = (slug: string,
    projectId: number,
    params?: ListGroupsParams,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}/groups`, ...(params ? [params] : [])
    ] as const;
    }


export const getListGroupsQueryOptions = <TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(slug: string,
    projectId: number,
    params?: ListGroupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGroupsQueryKey(slug,projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroups>>> = ({ signal }) => listGroups(slug,projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGroupsQueryResult = NonNullable<Awaited<ReturnType<typeof listGroups>>>
export type ListGroupsQueryError = unknown


export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 slug: string,
    projectId: number,
    params: undefined |  ListGroupsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroups>>,
          TError,
          Awaited<ReturnType<typeof listGroups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ListGroupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroups>>,
          TError,
          Awaited<ReturnType<typeof listGroups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ListGroupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 API 分组列表
 */

export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ListGroupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGroupsQueryOptions(slug,projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateGroupUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/groups`
}

/**
 * @summary 创建 API 分组
 */
export const createGroup = async (slug: string,
    projectId: number,
    createGroupBody: CreateGroupBody, options?: RequestInit): Promise<APIGroupResp> => {

  return customFetch<APIGroupResp>(getCreateGroupUrl(slug,projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createGroupBody)
  }
);}




export const getCreateGroupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{slug: string;projectId: number;data: CreateGroupBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{slug: string;projectId: number;data: CreateGroupBody}, TContext> => {

const mutationKey = ['createGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGroup>>, {slug: string;projectId: number;data: CreateGroupBody}> = (props) => {
          const {slug,projectId,data} = props ?? {};

          return  createGroup(slug,projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateGroupMutationResult = NonNullable<Awaited<ReturnType<typeof createGroup>>>
    export type CreateGroupMutationBody = CreateGroupBody
    export type CreateGroupMutationError = unknown

    /**
 * @summary 创建 API 分组
 */
export const useCreateGroup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{slug: string;projectId: number;data: CreateGroupBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGroup>>,
        TError,
        {slug: string;projectId: number;data: CreateGroupBody},
        TContext
      > => {
      return useMutation(getCreateGroupMutationOptions(options), queryClient);
    }
    export const getUpdateGroupUrl = (slug: string,
    projectId: number,
    groupId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/groups/${groupId}`
}

/**
 * @summary 更新 API 分组
 */
export const updateGroup = async (slug: string,
    projectId: number,
    groupId: number,
    updateGroupBody: UpdateGroupBody, options?: RequestInit): Promise<APIGroupResp> => {

  return customFetch<APIGroupResp>(getUpdateGroupUrl(slug,projectId,groupId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateGroupBody)
  }
);}




export const getUpdateGroupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroup>>, TError,{slug: string;projectId: number;groupId: number;data: UpdateGroupBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateGroup>>, TError,{slug: string;projectId: number;groupId: number;data: UpdateGroupBody}, TContext> => {

const mutationKey = ['updateGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGroup>>, {slug: string;projectId: number;groupId: number;data: UpdateGroupBody}> = (props) => {
          const {slug,projectId,groupId,data} = props ?? {};

          return  updateGroup(slug,projectId,groupId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateGroupMutationResult = NonNullable<Awaited<ReturnType<typeof updateGroup>>>
    export type UpdateGroupMutationBody = UpdateGroupBody
    export type UpdateGroupMutationError = unknown

    /**
 * @summary 更新 API 分组
 */
export const useUpdateGroup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroup>>, TError,{slug: string;projectId: number;groupId: number;data: UpdateGroupBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateGroup>>,
        TError,
        {slug: string;projectId: number;groupId: number;data: UpdateGroupBody},
        TContext
      > => {
      return useMutation(getUpdateGroupMutationOptions(options), queryClient);
    }
    export const getDeleteGroupUrl = (slug: string,
    projectId: number,
    groupId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/groups/${groupId}`
}

/**
 * @summary 删除 API 分组
 */
export const deleteGroup = async (slug: string,
    projectId: number,
    groupId: number, options?: RequestInit): Promise<DeleteGroup200> => {

  return customFetch<DeleteGroup200>(getDeleteGroupUrl(slug,projectId,groupId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteGroupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGroup>>, TError,{slug: string;projectId: number;groupId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteGroup>>, TError,{slug: string;projectId: number;groupId: number}, TContext> => {

const mutationKey = ['deleteGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGroup>>, {slug: string;projectId: number;groupId: number}> = (props) => {
          const {slug,projectId,groupId} = props ?? {};

          return  deleteGroup(slug,projectId,groupId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteGroupMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGroup>>>

    export type DeleteGroupMutationError = unknown

    /**
 * @summary 删除 API 分组
 */
export const useDeleteGroup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGroup>>, TError,{slug: string;projectId: number;groupId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteGroup>>,
        TError,
        {slug: string;projectId: number;groupId: number},
        TContext
      > => {
      return useMutation(getDeleteGroupMutationOptions(options), queryClient);
    }
