/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateDataSourceReq,
  DataSourceListResp,
  DataSourceResp,
  DeleteDataSource200,
  ListDataSourcesParams,
  TestDatasource200,
  TestDatasourceBody,
  UpdateDataSourceReq
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListDataSourcesUrl = (slug: string,
    params?: ListDataSourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/datasources?${stringifiedParams}` : `/v1/tenants/${slug}/datasources`
}

/**
 * @summary 获取数据源列表
 */
export const listDataSources = async (slug: string,
    params?: ListDataSourcesParams, options?: RequestInit): Promise<DataSourceListResp> => {

  return customFetch<DataSourceListResp>(getListDataSourcesUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDataSourcesQueryKey = (slug: string,
    params?: ListDataSourcesParams,) => {
    return [
    `/v1/tenants/${slug}/datasources`, ...(params ? [params] : [])
    ] as const;
    }


export const getListDataSourcesQueryOptions = <TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(slug: string,
    params?: ListDataSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDataSourcesQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDataSources>>> = ({ signal }) => listDataSources(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDataSourcesQueryResult = NonNullable<Awaited<ReturnType<typeof listDataSources>>>
export type ListDataSourcesQueryError = unknown


export function useListDataSources<TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(
 slug: string,
    params: undefined |  ListDataSourcesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDataSources>>,
          TError,
          Awaited<ReturnType<typeof listDataSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDataSources<TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(
 slug: string,
    params?: ListDataSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDataSources>>,
          TError,
          Awaited<ReturnType<typeof listDataSources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDataSources<TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(
 slug: string,
    params?: ListDataSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取数据源列表
 */

export function useListDataSources<TData = Awaited<ReturnType<typeof listDataSources>>, TError = unknown>(
 slug: string,
    params?: ListDataSourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDataSources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDataSourcesQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateDataSourceUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/datasources`
}

/**
 * @summary 创建数据源
 */
export const createDataSource = async (slug: string,
    createDataSourceReq: CreateDataSourceReq, options?: RequestInit): Promise<DataSourceResp> => {

  return customFetch<DataSourceResp>(getCreateDataSourceUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createDataSourceReq)
  }
);}




export const getCreateDataSourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDataSource>>, TError,{slug: string;data: CreateDataSourceReq}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createDataSource>>, TError,{slug: string;data: CreateDataSourceReq}, TContext> => {

const mutationKey = ['createDataSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDataSource>>, {slug: string;data: CreateDataSourceReq}> = (props) => {
          const {slug,data} = props ?? {};

          return  createDataSource(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDataSourceMutationResult = NonNullable<Awaited<ReturnType<typeof createDataSource>>>
    export type CreateDataSourceMutationBody = CreateDataSourceReq
    export type CreateDataSourceMutationError = unknown

    /**
 * @summary 创建数据源
 */
export const useCreateDataSource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDataSource>>, TError,{slug: string;data: CreateDataSourceReq}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDataSource>>,
        TError,
        {slug: string;data: CreateDataSourceReq},
        TContext
      > => {
      return useMutation(getCreateDataSourceMutationOptions(options), queryClient);
    }
    export const getTestDatasourceUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/datasources/test`
}

/**
 * @summary 测试数据源连接
 */
export const testDatasource = async (slug: string,
    testDatasourceBody: TestDatasourceBody, options?: RequestInit): Promise<TestDatasource200> => {

  return customFetch<TestDatasource200>(getTestDatasourceUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(testDatasourceBody)
  }
);}




export const getTestDatasourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testDatasource>>, TError,{slug: string;data: TestDatasourceBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof testDatasource>>, TError,{slug: string;data: TestDatasourceBody}, TContext> => {

const mutationKey = ['testDatasource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testDatasource>>, {slug: string;data: TestDatasourceBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  testDatasource(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestDatasourceMutationResult = NonNullable<Awaited<ReturnType<typeof testDatasource>>>
    export type TestDatasourceMutationBody = TestDatasourceBody
    export type TestDatasourceMutationError = unknown

    /**
 * @summary 测试数据源连接
 */
export const useTestDatasource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testDatasource>>, TError,{slug: string;data: TestDatasourceBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testDatasource>>,
        TError,
        {slug: string;data: TestDatasourceBody},
        TContext
      > => {
      return useMutation(getTestDatasourceMutationOptions(options), queryClient);
    }
    export const getGetDataSourceUrl = (slug: string,
    datasourceId: number,) => {




  return `/v1/tenants/${slug}/datasources/${datasourceId}`
}

/**
 * @summary 获取数据源详情
 */
export const getDataSource = async (slug: string,
    datasourceId: number, options?: RequestInit): Promise<DataSourceResp> => {

  return customFetch<DataSourceResp>(getGetDataSourceUrl(slug,datasourceId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDataSourceQueryKey = (slug: string,
    datasourceId: number,) => {
    return [
    `/v1/tenants/${slug}/datasources/${datasourceId}`
    ] as const;
    }


export const getGetDataSourceQueryOptions = <TData = Awaited<ReturnType<typeof getDataSource>>, TError = unknown>(slug: string,
    datasourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDataSourceQueryKey(slug,datasourceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDataSource>>> = ({ signal }) => getDataSource(slug,datasourceId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && datasourceId !== null && datasourceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDataSource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDataSourceQueryResult = NonNullable<Awaited<ReturnType<typeof getDataSource>>>
export type GetDataSourceQueryError = unknown


export function useGetDataSource<TData = Awaited<ReturnType<typeof getDataSource>>, TError = unknown>(
 slug: string,
    datasourceId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDataSource>>,
          TError,
          Awaited<ReturnType<typeof getDataSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDataSource<TData = Awaited<ReturnType<typeof getDataSource>>, TError = unknown>(
 slug: string,
    datasourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDataSource>>,
          TError,
          Awaited<ReturnType<typeof getDataSource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDataSource<TData = Awaited<ReturnType<typeof getDataSource>>, TError = unknown>(
 slug: string,
    datasourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取数据源详情
 */

export function useGetDataSource<TData = Awaited<ReturnType<typeof getDataSource>>, TError = unknown>(
 slug: string,
    datasourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDataSource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDataSourceQueryOptions(slug,datasourceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateDataSourceUrl = (slug: string,
    datasourceId: number,) => {




  return `/v1/tenants/${slug}/datasources/${datasourceId}`
}

/**
 * @summary 更新数据源
 */
export const updateDataSource = async (slug: string,
    datasourceId: number,
    updateDataSourceReq?: UpdateDataSourceReq, options?: RequestInit): Promise<DataSourceResp> => {

  return customFetch<DataSourceResp>(getUpdateDataSourceUrl(slug,datasourceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateDataSourceReq)
  }
);}




export const getUpdateDataSourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDataSource>>, TError,{slug: string;datasourceId: number;data?: UpdateDataSourceReq}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDataSource>>, TError,{slug: string;datasourceId: number;data?: UpdateDataSourceReq}, TContext> => {

const mutationKey = ['updateDataSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDataSource>>, {slug: string;datasourceId: number;data?: UpdateDataSourceReq}> = (props) => {
          const {slug,datasourceId,data} = props ?? {};

          return  updateDataSource(slug,datasourceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDataSourceMutationResult = NonNullable<Awaited<ReturnType<typeof updateDataSource>>>
    export type UpdateDataSourceMutationBody = UpdateDataSourceReq | undefined
    export type UpdateDataSourceMutationError = unknown

    /**
 * @summary 更新数据源
 */
export const useUpdateDataSource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDataSource>>, TError,{slug: string;datasourceId: number;data?: UpdateDataSourceReq}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDataSource>>,
        TError,
        {slug: string;datasourceId: number;data?: UpdateDataSourceReq},
        TContext
      > => {
      return useMutation(getUpdateDataSourceMutationOptions(options), queryClient);
    }
    export const getDeleteDataSourceUrl = (slug: string,
    datasourceId: number,) => {




  return `/v1/tenants/${slug}/datasources/${datasourceId}`
}

/**
 * @summary 删除数据源
 */
export const deleteDataSource = async (slug: string,
    datasourceId: number, options?: RequestInit): Promise<DeleteDataSource200> => {

  return customFetch<DeleteDataSource200>(getDeleteDataSourceUrl(slug,datasourceId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteDataSourceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSource>>, TError,{slug: string;datasourceId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDataSource>>, TError,{slug: string;datasourceId: number}, TContext> => {

const mutationKey = ['deleteDataSource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDataSource>>, {slug: string;datasourceId: number}> = (props) => {
          const {slug,datasourceId} = props ?? {};

          return  deleteDataSource(slug,datasourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDataSourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDataSource>>>

    export type DeleteDataSourceMutationError = unknown

    /**
 * @summary 删除数据源
 */
export const useDeleteDataSource = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDataSource>>, TError,{slug: string;datasourceId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDataSource>>,
        TError,
        {slug: string;datasourceId: number},
        TContext
      > => {
      return useMutation(getDeleteDataSourceMutationOptions(options), queryClient);
    }
