/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EndpointCallLogListResp,
  ListEndpointCallLogsParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListEndpointCallLogsUrl = (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointCallLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/call-logs?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/call-logs`
}

/**
 * 倒序列出指定接口最近的调用流水（成功+失败）。支持按状态码段、关键词、时间下限过滤
 * @summary 查询接口调用日志
 */
export const listEndpointCallLogs = async (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointCallLogsParams, options?: RequestInit): Promise<EndpointCallLogListResp> => {

  return customFetch<EndpointCallLogListResp>(getListEndpointCallLogsUrl(slug,projectId,endpointId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEndpointCallLogsQueryKey = (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointCallLogsParams,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/call-logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEndpointCallLogsQueryOptions = <TData = Awaited<ReturnType<typeof listEndpointCallLogs>>, TError = unknown>(slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointCallLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointCallLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEndpointCallLogsQueryKey(slug,projectId,endpointId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEndpointCallLogs>>> = ({ signal }) => listEndpointCallLogs(slug,projectId,endpointId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined && endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEndpointCallLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEndpointCallLogsQueryResult = NonNullable<Awaited<ReturnType<typeof listEndpointCallLogs>>>
export type ListEndpointCallLogsQueryError = unknown


export function useListEndpointCallLogs<TData = Awaited<ReturnType<typeof listEndpointCallLogs>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params: undefined |  ListEndpointCallLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointCallLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpointCallLogs>>,
          TError,
          Awaited<ReturnType<typeof listEndpointCallLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpointCallLogs<TData = Awaited<ReturnType<typeof listEndpointCallLogs>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointCallLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointCallLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpointCallLogs>>,
          TError,
          Awaited<ReturnType<typeof listEndpointCallLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpointCallLogs<TData = Awaited<ReturnType<typeof listEndpointCallLogs>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointCallLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointCallLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询接口调用日志
 */

export function useListEndpointCallLogs<TData = Awaited<ReturnType<typeof listEndpointCallLogs>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointCallLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointCallLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEndpointCallLogsQueryOptions(slug,projectId,endpointId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






