/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActivateEndpointVersion200,
  ActivateEndpointVersionParams,
  CreateEndpointVersionBody,
  DeleteEndpointVersion200,
  EndpointActivationLogListResp,
  EndpointActiveVersionResp,
  EndpointVersionListResp,
  EndpointVersionResp,
  ListEndpointActivationLogParams,
  ListEndpointVersionsParams,
  PromoteEndpointVersion200,
  PromoteEndpointVersionBody,
  PublishEndpointBody,
  PublishEndpointParams,
  RevertEndpointToActive200,
  RevertEndpointToActiveParams,
  UnpublishEndpoint200,
  UnpublishEndpointParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListEndpointActivationLogUrl = (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointActivationLogParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/activation-log?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/activation-log`
}

/**
 * @summary 查询接口激活流水
 */
export const listEndpointActivationLog = async (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointActivationLogParams, options?: RequestInit): Promise<EndpointActivationLogListResp> => {

  return customFetch<EndpointActivationLogListResp>(getListEndpointActivationLogUrl(slug,projectId,endpointId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEndpointActivationLogQueryKey = (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointActivationLogParams,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/activation-log`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEndpointActivationLogQueryOptions = <TData = Awaited<ReturnType<typeof listEndpointActivationLog>>, TError = unknown>(slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointActivationLogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActivationLog>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEndpointActivationLogQueryKey(slug,projectId,endpointId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEndpointActivationLog>>> = ({ signal }) => listEndpointActivationLog(slug,projectId,endpointId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined && endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEndpointActivationLog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEndpointActivationLogQueryResult = NonNullable<Awaited<ReturnType<typeof listEndpointActivationLog>>>
export type ListEndpointActivationLogQueryError = unknown


export function useListEndpointActivationLog<TData = Awaited<ReturnType<typeof listEndpointActivationLog>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params: undefined |  ListEndpointActivationLogParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActivationLog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpointActivationLog>>,
          TError,
          Awaited<ReturnType<typeof listEndpointActivationLog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpointActivationLog<TData = Awaited<ReturnType<typeof listEndpointActivationLog>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointActivationLogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActivationLog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpointActivationLog>>,
          TError,
          Awaited<ReturnType<typeof listEndpointActivationLog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpointActivationLog<TData = Awaited<ReturnType<typeof listEndpointActivationLog>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointActivationLogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActivationLog>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询接口激活流水
 */

export function useListEndpointActivationLog<TData = Awaited<ReturnType<typeof listEndpointActivationLog>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointActivationLogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActivationLog>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEndpointActivationLogQueryOptions(slug,projectId,endpointId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getListEndpointActivesUrl = (slug: string,
    projectId: number,
    endpointId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/actives`
}

/**
 * @summary 列出该接口在各 env 的当前激活版本（per-env 激活快照）
 */
export const listEndpointActives = async (slug: string,
    projectId: number,
    endpointId: number, options?: RequestInit): Promise<EndpointActiveVersionResp[]> => {

  return customFetch<EndpointActiveVersionResp[]>(getListEndpointActivesUrl(slug,projectId,endpointId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEndpointActivesQueryKey = (slug: string,
    projectId: number,
    endpointId: number,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/actives`
    ] as const;
    }


export const getListEndpointActivesQueryOptions = <TData = Awaited<ReturnType<typeof listEndpointActives>>, TError = unknown>(slug: string,
    projectId: number,
    endpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActives>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEndpointActivesQueryKey(slug,projectId,endpointId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEndpointActives>>> = ({ signal }) => listEndpointActives(slug,projectId,endpointId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined && endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEndpointActives>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEndpointActivesQueryResult = NonNullable<Awaited<ReturnType<typeof listEndpointActives>>>
export type ListEndpointActivesQueryError = unknown


export function useListEndpointActives<TData = Awaited<ReturnType<typeof listEndpointActives>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActives>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpointActives>>,
          TError,
          Awaited<ReturnType<typeof listEndpointActives>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpointActives<TData = Awaited<ReturnType<typeof listEndpointActives>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActives>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpointActives>>,
          TError,
          Awaited<ReturnType<typeof listEndpointActives>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpointActives<TData = Awaited<ReturnType<typeof listEndpointActives>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActives>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 列出该接口在各 env 的当前激活版本（per-env 激活快照）
 */

export function useListEndpointActives<TData = Awaited<ReturnType<typeof listEndpointActives>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointActives>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEndpointActivesQueryOptions(slug,projectId,endpointId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getPromoteEndpointVersionUrl = (slug: string,
    projectId: number,
    endpointId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/promote`
}

/**
 * @summary 把 source env 当前激活版本提升到 target env（无需新建 version）
 */
export const promoteEndpointVersion = async (slug: string,
    projectId: number,
    endpointId: number,
    promoteEndpointVersionBody: PromoteEndpointVersionBody, options?: RequestInit): Promise<PromoteEndpointVersion200> => {

  return customFetch<PromoteEndpointVersion200>(getPromoteEndpointVersionUrl(slug,projectId,endpointId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(promoteEndpointVersionBody)
  }
);}




export const getPromoteEndpointVersionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof promoteEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;data: PromoteEndpointVersionBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof promoteEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;data: PromoteEndpointVersionBody}, TContext> => {

const mutationKey = ['promoteEndpointVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof promoteEndpointVersion>>, {slug: string;projectId: number;endpointId: number;data: PromoteEndpointVersionBody}> = (props) => {
          const {slug,projectId,endpointId,data} = props ?? {};

          return  promoteEndpointVersion(slug,projectId,endpointId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PromoteEndpointVersionMutationResult = NonNullable<Awaited<ReturnType<typeof promoteEndpointVersion>>>
    export type PromoteEndpointVersionMutationBody = PromoteEndpointVersionBody
    export type PromoteEndpointVersionMutationError = unknown

    /**
 * @summary 把 source env 当前激活版本提升到 target env（无需新建 version）
 */
export const usePromoteEndpointVersion = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof promoteEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;data: PromoteEndpointVersionBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof promoteEndpointVersion>>,
        TError,
        {slug: string;projectId: number;endpointId: number;data: PromoteEndpointVersionBody},
        TContext
      > => {
      return useMutation(getPromoteEndpointVersionMutationOptions(options), queryClient);
    }
    export const getPublishEndpointUrl = (slug: string,
    projectId: number,
    endpointId: number,
    params?: PublishEndpointParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/publish?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/publish`
}

/**
 * @summary 在某 env 发布接口（创建版本 + 激活）
 */
export const publishEndpoint = async (slug: string,
    projectId: number,
    endpointId: number,
    publishEndpointBody?: PublishEndpointBody,
    params?: PublishEndpointParams, options?: RequestInit): Promise<EndpointVersionResp> => {

  return customFetch<EndpointVersionResp>(getPublishEndpointUrl(slug,projectId,endpointId,params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(publishEndpointBody)
  }
);}




export const getPublishEndpointMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data?: PublishEndpointBody;params?: PublishEndpointParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof publishEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data?: PublishEndpointBody;params?: PublishEndpointParams}, TContext> => {

const mutationKey = ['publishEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishEndpoint>>, {slug: string;projectId: number;endpointId: number;data?: PublishEndpointBody;params?: PublishEndpointParams}> = (props) => {
          const {slug,projectId,endpointId,data,params} = props ?? {};

          return  publishEndpoint(slug,projectId,endpointId,data,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof publishEndpoint>>>
    export type PublishEndpointMutationBody = PublishEndpointBody | undefined
    export type PublishEndpointMutationError = unknown

    /**
 * @summary 在某 env 发布接口（创建版本 + 激活）
 */
export const usePublishEndpoint = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data?: PublishEndpointBody;params?: PublishEndpointParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishEndpoint>>,
        TError,
        {slug: string;projectId: number;endpointId: number;data?: PublishEndpointBody;params?: PublishEndpointParams},
        TContext
      > => {
      return useMutation(getPublishEndpointMutationOptions(options), queryClient);
    }
    export const getRevertEndpointToActiveUrl = (slug: string,
    projectId: number,
    endpointId: number,
    params?: RevertEndpointToActiveParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/revert?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/revert`
}

/**
 * @summary 还原草稿到某 env 的当前激活版本（丢弃未发布修改）
 */
export const revertEndpointToActive = async (slug: string,
    projectId: number,
    endpointId: number,
    params?: RevertEndpointToActiveParams, options?: RequestInit): Promise<RevertEndpointToActive200> => {

  return customFetch<RevertEndpointToActive200>(getRevertEndpointToActiveUrl(slug,projectId,endpointId,params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getRevertEndpointToActiveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revertEndpointToActive>>, TError,{slug: string;projectId: number;endpointId: number;params?: RevertEndpointToActiveParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof revertEndpointToActive>>, TError,{slug: string;projectId: number;endpointId: number;params?: RevertEndpointToActiveParams}, TContext> => {

const mutationKey = ['revertEndpointToActive'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revertEndpointToActive>>, {slug: string;projectId: number;endpointId: number;params?: RevertEndpointToActiveParams}> = (props) => {
          const {slug,projectId,endpointId,params} = props ?? {};

          return  revertEndpointToActive(slug,projectId,endpointId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevertEndpointToActiveMutationResult = NonNullable<Awaited<ReturnType<typeof revertEndpointToActive>>>

    export type RevertEndpointToActiveMutationError = unknown

    /**
 * @summary 还原草稿到某 env 的当前激活版本（丢弃未发布修改）
 */
export const useRevertEndpointToActive = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revertEndpointToActive>>, TError,{slug: string;projectId: number;endpointId: number;params?: RevertEndpointToActiveParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revertEndpointToActive>>,
        TError,
        {slug: string;projectId: number;endpointId: number;params?: RevertEndpointToActiveParams},
        TContext
      > => {
      return useMutation(getRevertEndpointToActiveMutationOptions(options), queryClient);
    }
    export const getUnpublishEndpointUrl = (slug: string,
    projectId: number,
    endpointId: number,
    params?: UnpublishEndpointParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/unpublish?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/unpublish`
}

/**
 * @summary 在某 env 下线接口（清掉该 env 的激活指针）
 */
export const unpublishEndpoint = async (slug: string,
    projectId: number,
    endpointId: number,
    params?: UnpublishEndpointParams, options?: RequestInit): Promise<UnpublishEndpoint200> => {

  return customFetch<UnpublishEndpoint200>(getUnpublishEndpointUrl(slug,projectId,endpointId,params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getUnpublishEndpointMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unpublishEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;params?: UnpublishEndpointParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof unpublishEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;params?: UnpublishEndpointParams}, TContext> => {

const mutationKey = ['unpublishEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unpublishEndpoint>>, {slug: string;projectId: number;endpointId: number;params?: UnpublishEndpointParams}> = (props) => {
          const {slug,projectId,endpointId,params} = props ?? {};

          return  unpublishEndpoint(slug,projectId,endpointId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnpublishEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof unpublishEndpoint>>>

    export type UnpublishEndpointMutationError = unknown

    /**
 * @summary 在某 env 下线接口（清掉该 env 的激活指针）
 */
export const useUnpublishEndpoint = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unpublishEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;params?: UnpublishEndpointParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unpublishEndpoint>>,
        TError,
        {slug: string;projectId: number;endpointId: number;params?: UnpublishEndpointParams},
        TContext
      > => {
      return useMutation(getUnpublishEndpointMutationOptions(options), queryClient);
    }
    export const getListEndpointVersionsUrl = (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointVersionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/versions?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/versions`
}

/**
 * @summary 查询版本历史
 */
export const listEndpointVersions = async (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointVersionsParams, options?: RequestInit): Promise<EndpointVersionListResp> => {

  return customFetch<EndpointVersionListResp>(getListEndpointVersionsUrl(slug,projectId,endpointId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEndpointVersionsQueryKey = (slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointVersionsParams,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/versions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEndpointVersionsQueryOptions = <TData = Awaited<ReturnType<typeof listEndpointVersions>>, TError = unknown>(slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEndpointVersionsQueryKey(slug,projectId,endpointId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEndpointVersions>>> = ({ signal }) => listEndpointVersions(slug,projectId,endpointId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined && endpointId !== null && endpointId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEndpointVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEndpointVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof listEndpointVersions>>>
export type ListEndpointVersionsQueryError = unknown


export function useListEndpointVersions<TData = Awaited<ReturnType<typeof listEndpointVersions>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params: undefined |  ListEndpointVersionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpointVersions>>,
          TError,
          Awaited<ReturnType<typeof listEndpointVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpointVersions<TData = Awaited<ReturnType<typeof listEndpointVersions>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpointVersions>>,
          TError,
          Awaited<ReturnType<typeof listEndpointVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpointVersions<TData = Awaited<ReturnType<typeof listEndpointVersions>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询版本历史
 */

export function useListEndpointVersions<TData = Awaited<ReturnType<typeof listEndpointVersions>>, TError = unknown>(
 slug: string,
    projectId: number,
    endpointId: number,
    params?: ListEndpointVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpointVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEndpointVersionsQueryOptions(slug,projectId,endpointId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateEndpointVersionUrl = (slug: string,
    projectId: number,
    endpointId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/versions`
}

/**
 * @summary 创建版本快照（不激活任何 env）
 */
export const createEndpointVersion = async (slug: string,
    projectId: number,
    endpointId: number,
    createEndpointVersionBody?: CreateEndpointVersionBody, options?: RequestInit): Promise<EndpointVersionResp> => {

  return customFetch<EndpointVersionResp>(getCreateEndpointVersionUrl(slug,projectId,endpointId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createEndpointVersionBody)
  }
);}




export const getCreateEndpointVersionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;data?: CreateEndpointVersionBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;data?: CreateEndpointVersionBody}, TContext> => {

const mutationKey = ['createEndpointVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEndpointVersion>>, {slug: string;projectId: number;endpointId: number;data?: CreateEndpointVersionBody}> = (props) => {
          const {slug,projectId,endpointId,data} = props ?? {};

          return  createEndpointVersion(slug,projectId,endpointId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateEndpointVersionMutationResult = NonNullable<Awaited<ReturnType<typeof createEndpointVersion>>>
    export type CreateEndpointVersionMutationBody = CreateEndpointVersionBody | undefined
    export type CreateEndpointVersionMutationError = unknown

    /**
 * @summary 创建版本快照（不激活任何 env）
 */
export const useCreateEndpointVersion = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;data?: CreateEndpointVersionBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEndpointVersion>>,
        TError,
        {slug: string;projectId: number;endpointId: number;data?: CreateEndpointVersionBody},
        TContext
      > => {
      return useMutation(getCreateEndpointVersionMutationOptions(options), queryClient);
    }
    export const getDeleteEndpointVersionUrl = (slug: string,
    projectId: number,
    endpointId: number,
    versionId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/versions/${versionId}`
}

/**
 * 任何 env 仍激活该版本时不可删除
 * @summary 删除指定版本（不可恢复）
 */
export const deleteEndpointVersion = async (slug: string,
    projectId: number,
    endpointId: number,
    versionId: number, options?: RequestInit): Promise<DeleteEndpointVersion200> => {

  return customFetch<DeleteEndpointVersion200>(getDeleteEndpointVersionUrl(slug,projectId,endpointId,versionId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteEndpointVersionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;versionId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;versionId: number}, TContext> => {

const mutationKey = ['deleteEndpointVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEndpointVersion>>, {slug: string;projectId: number;endpointId: number;versionId: number}> = (props) => {
          const {slug,projectId,endpointId,versionId} = props ?? {};

          return  deleteEndpointVersion(slug,projectId,endpointId,versionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteEndpointVersionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEndpointVersion>>>

    export type DeleteEndpointVersionMutationError = unknown

    /**
 * @summary 删除指定版本（不可恢复）
 */
export const useDeleteEndpointVersion = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;versionId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEndpointVersion>>,
        TError,
        {slug: string;projectId: number;endpointId: number;versionId: number},
        TContext
      > => {
      return useMutation(getDeleteEndpointVersionMutationOptions(options), queryClient);
    }
    export const getActivateEndpointVersionUrl = (slug: string,
    projectId: number,
    endpointId: number,
    versionId: number,
    params?: ActivateEndpointVersionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/versions/${versionId}/activate?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}/versions/${versionId}/activate`
}

/**
 * @summary 在某 env 激活指定版本（=切换 / 回滚）
 */
export const activateEndpointVersion = async (slug: string,
    projectId: number,
    endpointId: number,
    versionId: number,
    params?: ActivateEndpointVersionParams, options?: RequestInit): Promise<ActivateEndpointVersion200> => {

  return customFetch<ActivateEndpointVersion200>(getActivateEndpointVersionUrl(slug,projectId,endpointId,versionId,params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getActivateEndpointVersionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;versionId: number;params?: ActivateEndpointVersionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof activateEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;versionId: number;params?: ActivateEndpointVersionParams}, TContext> => {

const mutationKey = ['activateEndpointVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateEndpointVersion>>, {slug: string;projectId: number;endpointId: number;versionId: number;params?: ActivateEndpointVersionParams}> = (props) => {
          const {slug,projectId,endpointId,versionId,params} = props ?? {};

          return  activateEndpointVersion(slug,projectId,endpointId,versionId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivateEndpointVersionMutationResult = NonNullable<Awaited<ReturnType<typeof activateEndpointVersion>>>

    export type ActivateEndpointVersionMutationError = unknown

    /**
 * @summary 在某 env 激活指定版本（=切换 / 回滚）
 */
export const useActivateEndpointVersion = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateEndpointVersion>>, TError,{slug: string;projectId: number;endpointId: number;versionId: number;params?: ActivateEndpointVersionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateEndpointVersion>>,
        TError,
        {slug: string;projectId: number;endpointId: number;versionId: number;params?: ActivateEndpointVersionParams},
        TContext
      > => {
      return useMutation(getActivateEndpointVersionMutationOptions(options), queryClient);
    }
