/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  APIEndpointListResp,
  APIEndpointResp,
  CreateEndpointBody,
  DeleteEndpoint200,
  ListEndpointsParams,
  PatchEndpointBody,
  UpdateEndpointBody
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListEndpointsUrl = (slug: string,
    projectId: number,
    params?: ListEndpointsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/endpoints?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/endpoints`
}

/**
 * @summary 获取 API 端点列表
 */
export const listEndpoints = async (slug: string,
    projectId: number,
    params?: ListEndpointsParams, options?: RequestInit): Promise<APIEndpointListResp> => {

  return customFetch<APIEndpointListResp>(getListEndpointsUrl(slug,projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEndpointsQueryKey = (slug: string,
    projectId: number,
    params?: ListEndpointsParams,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}/endpoints`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEndpointsQueryOptions = <TData = Awaited<ReturnType<typeof listEndpoints>>, TError = unknown>(slug: string,
    projectId: number,
    params?: ListEndpointsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpoints>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEndpointsQueryKey(slug,projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEndpoints>>> = ({ signal }) => listEndpoints(slug,projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEndpoints>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEndpointsQueryResult = NonNullable<Awaited<ReturnType<typeof listEndpoints>>>
export type ListEndpointsQueryError = unknown


export function useListEndpoints<TData = Awaited<ReturnType<typeof listEndpoints>>, TError = unknown>(
 slug: string,
    projectId: number,
    params: undefined |  ListEndpointsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpoints>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpoints>>,
          TError,
          Awaited<ReturnType<typeof listEndpoints>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpoints<TData = Awaited<ReturnType<typeof listEndpoints>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ListEndpointsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpoints>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndpoints>>,
          TError,
          Awaited<ReturnType<typeof listEndpoints>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEndpoints<TData = Awaited<ReturnType<typeof listEndpoints>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ListEndpointsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpoints>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 API 端点列表
 */

export function useListEndpoints<TData = Awaited<ReturnType<typeof listEndpoints>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ListEndpointsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndpoints>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEndpointsQueryOptions(slug,projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateEndpointUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/endpoints`
}

/**
 * @summary 创建 API 端点
 */
export const createEndpoint = async (slug: string,
    projectId: number,
    createEndpointBody: CreateEndpointBody, options?: RequestInit): Promise<APIEndpointResp> => {

  return customFetch<APIEndpointResp>(getCreateEndpointUrl(slug,projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createEndpointBody)
  }
);}




export const getCreateEndpointMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEndpoint>>, TError,{slug: string;projectId: number;data: CreateEndpointBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createEndpoint>>, TError,{slug: string;projectId: number;data: CreateEndpointBody}, TContext> => {

const mutationKey = ['createEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEndpoint>>, {slug: string;projectId: number;data: CreateEndpointBody}> = (props) => {
          const {slug,projectId,data} = props ?? {};

          return  createEndpoint(slug,projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof createEndpoint>>>
    export type CreateEndpointMutationBody = CreateEndpointBody
    export type CreateEndpointMutationError = unknown

    /**
 * @summary 创建 API 端点
 */
export const useCreateEndpoint = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEndpoint>>, TError,{slug: string;projectId: number;data: CreateEndpointBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEndpoint>>,
        TError,
        {slug: string;projectId: number;data: CreateEndpointBody},
        TContext
      > => {
      return useMutation(getCreateEndpointMutationOptions(options), queryClient);
    }
    export const getUpdateEndpointUrl = (slug: string,
    projectId: number,
    endpointId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}`
}

/**
 * @summary 更新 API 端点
 */
export const updateEndpoint = async (slug: string,
    projectId: number,
    endpointId: number,
    updateEndpointBody: UpdateEndpointBody, options?: RequestInit): Promise<APIEndpointResp> => {

  return customFetch<APIEndpointResp>(getUpdateEndpointUrl(slug,projectId,endpointId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateEndpointBody)
  }
);}




export const getUpdateEndpointMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data: UpdateEndpointBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data: UpdateEndpointBody}, TContext> => {

const mutationKey = ['updateEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEndpoint>>, {slug: string;projectId: number;endpointId: number;data: UpdateEndpointBody}> = (props) => {
          const {slug,projectId,endpointId,data} = props ?? {};

          return  updateEndpoint(slug,projectId,endpointId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof updateEndpoint>>>
    export type UpdateEndpointMutationBody = UpdateEndpointBody
    export type UpdateEndpointMutationError = unknown

    /**
 * @summary 更新 API 端点
 */
export const useUpdateEndpoint = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data: UpdateEndpointBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEndpoint>>,
        TError,
        {slug: string;projectId: number;endpointId: number;data: UpdateEndpointBody},
        TContext
      > => {
      return useMutation(getUpdateEndpointMutationOptions(options), queryClient);
    }
    export const getDeleteEndpointUrl = (slug: string,
    projectId: number,
    endpointId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}`
}

/**
 * @summary 删除 API 端点
 */
export const deleteEndpoint = async (slug: string,
    projectId: number,
    endpointId: number, options?: RequestInit): Promise<DeleteEndpoint200> => {

  return customFetch<DeleteEndpoint200>(getDeleteEndpointUrl(slug,projectId,endpointId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteEndpointMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEndpoint>>, TError,{slug: string;projectId: number;endpointId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEndpoint>>, TError,{slug: string;projectId: number;endpointId: number}, TContext> => {

const mutationKey = ['deleteEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEndpoint>>, {slug: string;projectId: number;endpointId: number}> = (props) => {
          const {slug,projectId,endpointId} = props ?? {};

          return  deleteEndpoint(slug,projectId,endpointId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEndpoint>>>

    export type DeleteEndpointMutationError = unknown

    /**
 * @summary 删除 API 端点
 */
export const useDeleteEndpoint = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEndpoint>>, TError,{slug: string;projectId: number;endpointId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEndpoint>>,
        TError,
        {slug: string;projectId: number;endpointId: number},
        TContext
      > => {
      return useMutation(getDeleteEndpointMutationOptions(options), queryClient);
    }
    export const getPatchEndpointUrl = (slug: string,
    projectId: number,
    endpointId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/endpoints/${endpointId}`
}

/**
 * @summary 局部更新 API 端点（仅 group_id 等可选字段）
 */
export const patchEndpoint = async (slug: string,
    projectId: number,
    endpointId: number,
    patchEndpointBody?: PatchEndpointBody, options?: RequestInit): Promise<APIEndpointResp> => {

  return customFetch<APIEndpointResp>(getPatchEndpointUrl(slug,projectId,endpointId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchEndpointBody)
  }
);}




export const getPatchEndpointMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data?: PatchEndpointBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof patchEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data?: PatchEndpointBody}, TContext> => {

const mutationKey = ['patchEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchEndpoint>>, {slug: string;projectId: number;endpointId: number;data?: PatchEndpointBody}> = (props) => {
          const {slug,projectId,endpointId,data} = props ?? {};

          return  patchEndpoint(slug,projectId,endpointId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof patchEndpoint>>>
    export type PatchEndpointMutationBody = PatchEndpointBody | undefined
    export type PatchEndpointMutationError = unknown

    /**
 * @summary 局部更新 API 端点（仅 group_id 等可选字段）
 */
export const usePatchEndpoint = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchEndpoint>>, TError,{slug: string;projectId: number;endpointId: number;data?: PatchEndpointBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchEndpoint>>,
        TError,
        {slug: string;projectId: number;endpointId: number;data?: PatchEndpointBody},
        TContext
      > => {
      return useMutation(getPatchEndpointMutationOptions(options), queryClient);
    }
