/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateGatewayBody,
  DeleteGateway200,
  ExecuteQuery200,
  ExecuteQueryBody,
  ExecuteQueryDelete200,
  ExecuteQueryDeleteBody,
  ExecuteQueryPost200,
  ExecuteQueryPostBody,
  ExecuteQueryPut200,
  ExecuteQueryPutBody,
  GatewayListResp,
  GatewayResp,
  ListGatewaysParams
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getExecuteQueryUrl = (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,) => {




  return `/-/${env}/${tenantSlug}/${projectSlug}/${path}`
}

/**
 * @summary 执行已发布的 API 接口
 */
export const executeQuery = async (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryBody?: ExecuteQueryBody, options?: RequestInit): Promise<ExecuteQuery200> => {

  return customFetch<ExecuteQuery200>(getExecuteQueryUrl(env,tenantSlug,projectSlug,path),
  {
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(executeQueryBody)
  }
);}





export const getExecuteQueryQueryKey = (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryBody?: ExecuteQueryBody,) => {
    return [
    `/-/${env}/${tenantSlug}/${projectSlug}/${path}`, executeQueryBody
    ] as const;
    }


export const getExecuteQueryQueryOptions = <TData = Awaited<ReturnType<typeof executeQuery>>, TError = unknown>(env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryBody?: ExecuteQueryBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof executeQuery>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExecuteQueryQueryKey(env,tenantSlug,projectSlug,path,executeQueryBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof executeQuery>>> = ({ signal }) => executeQuery(env,tenantSlug,projectSlug,path,executeQueryBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: env !== null && env !== undefined && tenantSlug !== null && tenantSlug !== undefined && projectSlug !== null && projectSlug !== undefined && path !== null && path !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof executeQuery>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExecuteQueryQueryResult = NonNullable<Awaited<ReturnType<typeof executeQuery>>>
export type ExecuteQueryQueryError = unknown


export function useExecuteQuery<TData = Awaited<ReturnType<typeof executeQuery>>, TError = unknown>(
 env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryBody: undefined |  ExecuteQueryBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof executeQuery>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof executeQuery>>,
          TError,
          Awaited<ReturnType<typeof executeQuery>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExecuteQuery<TData = Awaited<ReturnType<typeof executeQuery>>, TError = unknown>(
 env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryBody?: ExecuteQueryBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof executeQuery>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof executeQuery>>,
          TError,
          Awaited<ReturnType<typeof executeQuery>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExecuteQuery<TData = Awaited<ReturnType<typeof executeQuery>>, TError = unknown>(
 env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryBody?: ExecuteQueryBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof executeQuery>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 执行已发布的 API 接口
 */

export function useExecuteQuery<TData = Awaited<ReturnType<typeof executeQuery>>, TError = unknown>(
 env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryBody?: ExecuteQueryBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof executeQuery>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExecuteQueryQueryOptions(env,tenantSlug,projectSlug,path,executeQueryBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getExecuteQueryPutUrl = (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,) => {




  return `/-/${env}/${tenantSlug}/${projectSlug}/${path}`
}

/**
 * @summary 执行已发布的 API 接口
 */
export const executeQueryPut = async (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryPutBody?: ExecuteQueryPutBody, options?: RequestInit): Promise<ExecuteQueryPut200> => {

  return customFetch<ExecuteQueryPut200>(getExecuteQueryPutUrl(env,tenantSlug,projectSlug,path),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(executeQueryPutBody)
  }
);}




export const getExecuteQueryPutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeQueryPut>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPutBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof executeQueryPut>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPutBody}, TContext> => {

const mutationKey = ['executeQueryPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof executeQueryPut>>, {env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPutBody}> = (props) => {
          const {env,tenantSlug,projectSlug,path,data} = props ?? {};

          return  executeQueryPut(env,tenantSlug,projectSlug,path,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecuteQueryPutMutationResult = NonNullable<Awaited<ReturnType<typeof executeQueryPut>>>
    export type ExecuteQueryPutMutationBody = ExecuteQueryPutBody | undefined
    export type ExecuteQueryPutMutationError = unknown

    /**
 * @summary 执行已发布的 API 接口
 */
export const useExecuteQueryPut = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeQueryPut>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPutBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof executeQueryPut>>,
        TError,
        {env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPutBody},
        TContext
      > => {
      return useMutation(getExecuteQueryPutMutationOptions(options), queryClient);
    }
    export const getExecuteQueryPostUrl = (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,) => {




  return `/-/${env}/${tenantSlug}/${projectSlug}/${path}`
}

/**
 * @summary 执行已发布的 API 接口
 */
export const executeQueryPost = async (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryPostBody?: ExecuteQueryPostBody, options?: RequestInit): Promise<ExecuteQueryPost200> => {

  return customFetch<ExecuteQueryPost200>(getExecuteQueryPostUrl(env,tenantSlug,projectSlug,path),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(executeQueryPostBody)
  }
);}




export const getExecuteQueryPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeQueryPost>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPostBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof executeQueryPost>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPostBody}, TContext> => {

const mutationKey = ['executeQueryPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof executeQueryPost>>, {env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPostBody}> = (props) => {
          const {env,tenantSlug,projectSlug,path,data} = props ?? {};

          return  executeQueryPost(env,tenantSlug,projectSlug,path,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecuteQueryPostMutationResult = NonNullable<Awaited<ReturnType<typeof executeQueryPost>>>
    export type ExecuteQueryPostMutationBody = ExecuteQueryPostBody | undefined
    export type ExecuteQueryPostMutationError = unknown

    /**
 * @summary 执行已发布的 API 接口
 */
export const useExecuteQueryPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeQueryPost>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPostBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof executeQueryPost>>,
        TError,
        {env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryPostBody},
        TContext
      > => {
      return useMutation(getExecuteQueryPostMutationOptions(options), queryClient);
    }
    export const getExecuteQueryDeleteUrl = (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,) => {




  return `/-/${env}/${tenantSlug}/${projectSlug}/${path}`
}

/**
 * @summary 执行已发布的 API 接口
 */
export const executeQueryDelete = async (env: string,
    tenantSlug: string,
    projectSlug: string,
    path: string,
    executeQueryDeleteBody?: ExecuteQueryDeleteBody, options?: RequestInit): Promise<ExecuteQueryDelete200> => {

  return customFetch<ExecuteQueryDelete200>(getExecuteQueryDeleteUrl(env,tenantSlug,projectSlug,path),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(executeQueryDeleteBody)
  }
);}




export const getExecuteQueryDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeQueryDelete>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryDeleteBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof executeQueryDelete>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryDeleteBody}, TContext> => {

const mutationKey = ['executeQueryDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof executeQueryDelete>>, {env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryDeleteBody}> = (props) => {
          const {env,tenantSlug,projectSlug,path,data} = props ?? {};

          return  executeQueryDelete(env,tenantSlug,projectSlug,path,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExecuteQueryDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof executeQueryDelete>>>
    export type ExecuteQueryDeleteMutationBody = ExecuteQueryDeleteBody | undefined
    export type ExecuteQueryDeleteMutationError = unknown

    /**
 * @summary 执行已发布的 API 接口
 */
export const useExecuteQueryDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof executeQueryDelete>>, TError,{env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryDeleteBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof executeQueryDelete>>,
        TError,
        {env: string;tenantSlug: string;projectSlug: string;path: string;data?: ExecuteQueryDeleteBody},
        TContext
      > => {
      return useMutation(getExecuteQueryDeleteMutationOptions(options), queryClient);
    }
    export const getListGatewaysUrl = (slug: string,
    params?: ListGatewaysParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/gateways?${stringifiedParams}` : `/v1/tenants/${slug}/gateways`
}

/**
 * @summary 获取网关列表
 */
export const listGateways = async (slug: string,
    params?: ListGatewaysParams, options?: RequestInit): Promise<GatewayListResp> => {

  return customFetch<GatewayListResp>(getListGatewaysUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListGatewaysQueryKey = (slug: string,
    params?: ListGatewaysParams,) => {
    return [
    `/v1/tenants/${slug}/gateways`, ...(params ? [params] : [])
    ] as const;
    }


export const getListGatewaysQueryOptions = <TData = Awaited<ReturnType<typeof listGateways>>, TError = unknown>(slug: string,
    params?: ListGatewaysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGateways>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGatewaysQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGateways>>> = ({ signal }) => listGateways(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGateways>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGatewaysQueryResult = NonNullable<Awaited<ReturnType<typeof listGateways>>>
export type ListGatewaysQueryError = unknown


export function useListGateways<TData = Awaited<ReturnType<typeof listGateways>>, TError = unknown>(
 slug: string,
    params: undefined |  ListGatewaysParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGateways>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGateways>>,
          TError,
          Awaited<ReturnType<typeof listGateways>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGateways<TData = Awaited<ReturnType<typeof listGateways>>, TError = unknown>(
 slug: string,
    params?: ListGatewaysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGateways>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGateways>>,
          TError,
          Awaited<ReturnType<typeof listGateways>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGateways<TData = Awaited<ReturnType<typeof listGateways>>, TError = unknown>(
 slug: string,
    params?: ListGatewaysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGateways>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取网关列表
 */

export function useListGateways<TData = Awaited<ReturnType<typeof listGateways>>, TError = unknown>(
 slug: string,
    params?: ListGatewaysParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGateways>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGatewaysQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateGatewayUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/gateways`
}

/**
 * @summary 创建网关
 */
export const createGateway = async (slug: string,
    createGatewayBody: CreateGatewayBody, options?: RequestInit): Promise<GatewayResp> => {

  return customFetch<GatewayResp>(getCreateGatewayUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createGatewayBody)
  }
);}




export const getCreateGatewayMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGateway>>, TError,{slug: string;data: CreateGatewayBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createGateway>>, TError,{slug: string;data: CreateGatewayBody}, TContext> => {

const mutationKey = ['createGateway'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGateway>>, {slug: string;data: CreateGatewayBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  createGateway(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateGatewayMutationResult = NonNullable<Awaited<ReturnType<typeof createGateway>>>
    export type CreateGatewayMutationBody = CreateGatewayBody
    export type CreateGatewayMutationError = unknown

    /**
 * @summary 创建网关
 */
export const useCreateGateway = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGateway>>, TError,{slug: string;data: CreateGatewayBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGateway>>,
        TError,
        {slug: string;data: CreateGatewayBody},
        TContext
      > => {
      return useMutation(getCreateGatewayMutationOptions(options), queryClient);
    }
    export const getGetGatewayUrl = (slug: string,
    gatewayId: number,) => {




  return `/v1/tenants/${slug}/gateways/${gatewayId}`
}

/**
 * @summary 获取网关详情
 */
export const getGateway = async (slug: string,
    gatewayId: number, options?: RequestInit): Promise<GatewayResp> => {

  return customFetch<GatewayResp>(getGetGatewayUrl(slug,gatewayId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGatewayQueryKey = (slug: string,
    gatewayId: number,) => {
    return [
    `/v1/tenants/${slug}/gateways/${gatewayId}`
    ] as const;
    }


export const getGetGatewayQueryOptions = <TData = Awaited<ReturnType<typeof getGateway>>, TError = unknown>(slug: string,
    gatewayId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGateway>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGatewayQueryKey(slug,gatewayId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGateway>>> = ({ signal }) => getGateway(slug,gatewayId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && gatewayId !== null && gatewayId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGateway>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGatewayQueryResult = NonNullable<Awaited<ReturnType<typeof getGateway>>>
export type GetGatewayQueryError = unknown


export function useGetGateway<TData = Awaited<ReturnType<typeof getGateway>>, TError = unknown>(
 slug: string,
    gatewayId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGateway>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGateway>>,
          TError,
          Awaited<ReturnType<typeof getGateway>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGateway<TData = Awaited<ReturnType<typeof getGateway>>, TError = unknown>(
 slug: string,
    gatewayId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGateway>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGateway>>,
          TError,
          Awaited<ReturnType<typeof getGateway>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGateway<TData = Awaited<ReturnType<typeof getGateway>>, TError = unknown>(
 slug: string,
    gatewayId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGateway>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取网关详情
 */

export function useGetGateway<TData = Awaited<ReturnType<typeof getGateway>>, TError = unknown>(
 slug: string,
    gatewayId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGateway>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGatewayQueryOptions(slug,gatewayId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getDeleteGatewayUrl = (slug: string,
    gatewayId: number,) => {




  return `/v1/tenants/${slug}/gateways/${gatewayId}`
}

/**
 * @summary 删除网关
 */
export const deleteGateway = async (slug: string,
    gatewayId: number, options?: RequestInit): Promise<DeleteGateway200> => {

  return customFetch<DeleteGateway200>(getDeleteGatewayUrl(slug,gatewayId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteGatewayMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGateway>>, TError,{slug: string;gatewayId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteGateway>>, TError,{slug: string;gatewayId: number}, TContext> => {

const mutationKey = ['deleteGateway'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGateway>>, {slug: string;gatewayId: number}> = (props) => {
          const {slug,gatewayId} = props ?? {};

          return  deleteGateway(slug,gatewayId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteGatewayMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGateway>>>

    export type DeleteGatewayMutationError = unknown

    /**
 * @summary 删除网关
 */
export const useDeleteGateway = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGateway>>, TError,{slug: string;gatewayId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteGateway>>,
        TError,
        {slug: string;gatewayId: number},
        TContext
      > => {
      return useMutation(getDeleteGatewayMutationOptions(options), queryClient);
    }
