/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActivityListResp,
  GetOverviewActivityParams,
  GetOverviewTrafficParams,
  TrafficSeriesResp
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetOverviewActivityUrl = (slug: string,
    params?: GetOverviewActivityParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/overview/activity?${stringifiedParams}` : `/v1/tenants/${slug}/overview/activity`
}

/**
 * 合并资产变更事件（发布/激活/回滚等）与流量异常（5xx / 慢查询），按时间倒序返回当前租户的最近动态。
 * @summary 概览最近动态
 */
export const getOverviewActivity = async (slug: string,
    params?: GetOverviewActivityParams, options?: RequestInit): Promise<ActivityListResp> => {

  return customFetch<ActivityListResp>(getGetOverviewActivityUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOverviewActivityQueryKey = (slug: string,
    params?: GetOverviewActivityParams,) => {
    return [
    `/v1/tenants/${slug}/overview/activity`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetOverviewActivityQueryOptions = <TData = Awaited<ReturnType<typeof getOverviewActivity>>, TError = unknown>(slug: string,
    params?: GetOverviewActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewActivity>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOverviewActivityQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOverviewActivity>>> = ({ signal }) => getOverviewActivity(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOverviewActivity>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOverviewActivityQueryResult = NonNullable<Awaited<ReturnType<typeof getOverviewActivity>>>
export type GetOverviewActivityQueryError = unknown


export function useGetOverviewActivity<TData = Awaited<ReturnType<typeof getOverviewActivity>>, TError = unknown>(
 slug: string,
    params: undefined |  GetOverviewActivityParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewActivity>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewActivity>>,
          TError,
          Awaited<ReturnType<typeof getOverviewActivity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOverviewActivity<TData = Awaited<ReturnType<typeof getOverviewActivity>>, TError = unknown>(
 slug: string,
    params?: GetOverviewActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewActivity>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewActivity>>,
          TError,
          Awaited<ReturnType<typeof getOverviewActivity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOverviewActivity<TData = Awaited<ReturnType<typeof getOverviewActivity>>, TError = unknown>(
 slug: string,
    params?: GetOverviewActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewActivity>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 概览最近动态
 */

export function useGetOverviewActivity<TData = Awaited<ReturnType<typeof getOverviewActivity>>, TError = unknown>(
 slug: string,
    params?: GetOverviewActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewActivity>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOverviewActivityQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetOverviewTrafficUrl = (slug: string,
    params?: GetOverviewTrafficParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/overview/traffic?${stringifiedParams}` : `/v1/tenants/${slug}/overview/traffic`
}

/**
 * 按时间桶聚合当前租户在选定时间范围内的接口调用量（总请求数 + 错误数），用于概览页流量趋势图。空桶补零，返回连续序列。
 * @summary 概览流量趋势
 */
export const getOverviewTraffic = async (slug: string,
    params?: GetOverviewTrafficParams, options?: RequestInit): Promise<TrafficSeriesResp> => {

  return customFetch<TrafficSeriesResp>(getGetOverviewTrafficUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOverviewTrafficQueryKey = (slug: string,
    params?: GetOverviewTrafficParams,) => {
    return [
    `/v1/tenants/${slug}/overview/traffic`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetOverviewTrafficQueryOptions = <TData = Awaited<ReturnType<typeof getOverviewTraffic>>, TError = unknown>(slug: string,
    params?: GetOverviewTrafficParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewTraffic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOverviewTrafficQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOverviewTraffic>>> = ({ signal }) => getOverviewTraffic(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOverviewTraffic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOverviewTrafficQueryResult = NonNullable<Awaited<ReturnType<typeof getOverviewTraffic>>>
export type GetOverviewTrafficQueryError = unknown


export function useGetOverviewTraffic<TData = Awaited<ReturnType<typeof getOverviewTraffic>>, TError = unknown>(
 slug: string,
    params: undefined |  GetOverviewTrafficParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewTraffic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewTraffic>>,
          TError,
          Awaited<ReturnType<typeof getOverviewTraffic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOverviewTraffic<TData = Awaited<ReturnType<typeof getOverviewTraffic>>, TError = unknown>(
 slug: string,
    params?: GetOverviewTrafficParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewTraffic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewTraffic>>,
          TError,
          Awaited<ReturnType<typeof getOverviewTraffic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOverviewTraffic<TData = Awaited<ReturnType<typeof getOverviewTraffic>>, TError = unknown>(
 slug: string,
    params?: GetOverviewTrafficParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewTraffic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 概览流量趋势
 */

export function useGetOverviewTraffic<TData = Awaited<ReturnType<typeof getOverviewTraffic>>, TError = unknown>(
 slug: string,
    params?: GetOverviewTrafficParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOverviewTraffic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOverviewTrafficQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






