/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePlatformScriptBody,
  DeletePlatformScript200,
  ListPlatformScriptsParams,
  PlatformSettingsResp,
  ScriptListResp,
  ScriptResp,
  TenantEEConfigResp,
  UpdatePlatformScriptBody,
  UpdatePlatformSettingsBody,
  UpsertTenantEEConfigBody
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListPlatformScriptsUrl = (params?: ListPlatformScriptsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/platform/scripts?${stringifiedParams}` : `/v1/platform/scripts`
}

/**
 * @summary 获取平台内置脚本列表（仅超管）
 */
export const listPlatformScripts = async (params?: ListPlatformScriptsParams, options?: RequestInit): Promise<ScriptListResp> => {

  return customFetch<ScriptListResp>(getListPlatformScriptsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPlatformScriptsQueryKey = (params?: ListPlatformScriptsParams,) => {
    return [
    `/v1/platform/scripts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPlatformScriptsQueryOptions = <TData = Awaited<ReturnType<typeof listPlatformScripts>>, TError = unknown>(params?: ListPlatformScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformScripts>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPlatformScriptsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlatformScripts>>> = ({ signal }) => listPlatformScripts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPlatformScripts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPlatformScriptsQueryResult = NonNullable<Awaited<ReturnType<typeof listPlatformScripts>>>
export type ListPlatformScriptsQueryError = unknown


export function useListPlatformScripts<TData = Awaited<ReturnType<typeof listPlatformScripts>>, TError = unknown>(
 params: undefined |  ListPlatformScriptsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformScripts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlatformScripts>>,
          TError,
          Awaited<ReturnType<typeof listPlatformScripts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPlatformScripts<TData = Awaited<ReturnType<typeof listPlatformScripts>>, TError = unknown>(
 params?: ListPlatformScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformScripts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlatformScripts>>,
          TError,
          Awaited<ReturnType<typeof listPlatformScripts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPlatformScripts<TData = Awaited<ReturnType<typeof listPlatformScripts>>, TError = unknown>(
 params?: ListPlatformScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformScripts>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取平台内置脚本列表（仅超管）
 */

export function useListPlatformScripts<TData = Awaited<ReturnType<typeof listPlatformScripts>>, TError = unknown>(
 params?: ListPlatformScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlatformScripts>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPlatformScriptsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreatePlatformScriptUrl = () => {




  return `/v1/platform/scripts`
}

/**
 * @summary 创建平台内置脚本（仅超管）
 */
export const createPlatformScript = async (createPlatformScriptBody: CreatePlatformScriptBody, options?: RequestInit): Promise<ScriptResp> => {

  return customFetch<ScriptResp>(getCreatePlatformScriptUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPlatformScriptBody)
  }
);}




export const getCreatePlatformScriptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlatformScript>>, TError,{data: CreatePlatformScriptBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPlatformScript>>, TError,{data: CreatePlatformScriptBody}, TContext> => {

const mutationKey = ['createPlatformScript'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPlatformScript>>, {data: CreatePlatformScriptBody}> = (props) => {
          const {data} = props ?? {};

          return  createPlatformScript(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePlatformScriptMutationResult = NonNullable<Awaited<ReturnType<typeof createPlatformScript>>>
    export type CreatePlatformScriptMutationBody = CreatePlatformScriptBody
    export type CreatePlatformScriptMutationError = unknown

    /**
 * @summary 创建平台内置脚本（仅超管）
 */
export const useCreatePlatformScript = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPlatformScript>>, TError,{data: CreatePlatformScriptBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPlatformScript>>,
        TError,
        {data: CreatePlatformScriptBody},
        TContext
      > => {
      return useMutation(getCreatePlatformScriptMutationOptions(options), queryClient);
    }
    export const getUpdatePlatformScriptUrl = (scriptId: number,) => {




  return `/v1/platform/scripts/${scriptId}`
}

/**
 * @summary 更新平台内置脚本（仅超管）
 */
export const updatePlatformScript = async (scriptId: number,
    updatePlatformScriptBody?: UpdatePlatformScriptBody, options?: RequestInit): Promise<ScriptResp> => {

  return customFetch<ScriptResp>(getUpdatePlatformScriptUrl(scriptId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePlatformScriptBody)
  }
);}




export const getUpdatePlatformScriptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlatformScript>>, TError,{scriptId: number;data?: UpdatePlatformScriptBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlatformScript>>, TError,{scriptId: number;data?: UpdatePlatformScriptBody}, TContext> => {

const mutationKey = ['updatePlatformScript'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlatformScript>>, {scriptId: number;data?: UpdatePlatformScriptBody}> = (props) => {
          const {scriptId,data} = props ?? {};

          return  updatePlatformScript(scriptId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlatformScriptMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlatformScript>>>
    export type UpdatePlatformScriptMutationBody = UpdatePlatformScriptBody | undefined
    export type UpdatePlatformScriptMutationError = unknown

    /**
 * @summary 更新平台内置脚本（仅超管）
 */
export const useUpdatePlatformScript = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlatformScript>>, TError,{scriptId: number;data?: UpdatePlatformScriptBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlatformScript>>,
        TError,
        {scriptId: number;data?: UpdatePlatformScriptBody},
        TContext
      > => {
      return useMutation(getUpdatePlatformScriptMutationOptions(options), queryClient);
    }
    export const getDeletePlatformScriptUrl = (scriptId: number,) => {




  return `/v1/platform/scripts/${scriptId}`
}

/**
 * @summary 删除平台内置脚本（仅超管）
 */
export const deletePlatformScript = async (scriptId: number, options?: RequestInit): Promise<DeletePlatformScript200> => {

  return customFetch<DeletePlatformScript200>(getDeletePlatformScriptUrl(scriptId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeletePlatformScriptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlatformScript>>, TError,{scriptId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePlatformScript>>, TError,{scriptId: number}, TContext> => {

const mutationKey = ['deletePlatformScript'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePlatformScript>>, {scriptId: number}> = (props) => {
          const {scriptId} = props ?? {};

          return  deletePlatformScript(scriptId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePlatformScriptMutationResult = NonNullable<Awaited<ReturnType<typeof deletePlatformScript>>>

    export type DeletePlatformScriptMutationError = unknown

    /**
 * @summary 删除平台内置脚本（仅超管）
 */
export const useDeletePlatformScript = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlatformScript>>, TError,{scriptId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePlatformScript>>,
        TError,
        {scriptId: number},
        TContext
      > => {
      return useMutation(getDeletePlatformScriptMutationOptions(options), queryClient);
    }
    export const getGetPlatformSettingsUrl = () => {




  return `/v1/platform/settings`
}

/**
 * @summary 获取平台设置
 */
export const getPlatformSettings = async ( options?: RequestInit): Promise<PlatformSettingsResp> => {

  return customFetch<PlatformSettingsResp>(getGetPlatformSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPlatformSettingsQueryKey = () => {
    return [
    `/v1/platform/settings`
    ] as const;
    }


export const getGetPlatformSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getPlatformSettings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSettings>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlatformSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlatformSettings>>> = ({ signal }) => getPlatformSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlatformSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlatformSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getPlatformSettings>>>
export type GetPlatformSettingsQueryError = unknown


export function useGetPlatformSettings<TData = Awaited<ReturnType<typeof getPlatformSettings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlatformSettings>>,
          TError,
          Awaited<ReturnType<typeof getPlatformSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlatformSettings<TData = Awaited<ReturnType<typeof getPlatformSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlatformSettings>>,
          TError,
          Awaited<ReturnType<typeof getPlatformSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlatformSettings<TData = Awaited<ReturnType<typeof getPlatformSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSettings>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取平台设置
 */

export function useGetPlatformSettings<TData = Awaited<ReturnType<typeof getPlatformSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlatformSettings>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlatformSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdatePlatformSettingsUrl = () => {




  return `/v1/platform/settings`
}

/**
 * @summary 更新平台设置
 */
export const updatePlatformSettings = async (updatePlatformSettingsBody: UpdatePlatformSettingsBody, options?: RequestInit): Promise<PlatformSettingsResp> => {

  return customFetch<PlatformSettingsResp>(getUpdatePlatformSettingsUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePlatformSettingsBody)
  }
);}




export const getUpdatePlatformSettingsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlatformSettings>>, TError,{data: UpdatePlatformSettingsBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePlatformSettings>>, TError,{data: UpdatePlatformSettingsBody}, TContext> => {

const mutationKey = ['updatePlatformSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePlatformSettings>>, {data: UpdatePlatformSettingsBody}> = (props) => {
          const {data} = props ?? {};

          return  updatePlatformSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePlatformSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlatformSettings>>>
    export type UpdatePlatformSettingsMutationBody = UpdatePlatformSettingsBody
    export type UpdatePlatformSettingsMutationError = unknown

    /**
 * @summary 更新平台设置
 */
export const useUpdatePlatformSettings = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePlatformSettings>>, TError,{data: UpdatePlatformSettingsBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePlatformSettings>>,
        TError,
        {data: UpdatePlatformSettingsBody},
        TContext
      > => {
      return useMutation(getUpdatePlatformSettingsMutationOptions(options), queryClient);
    }
    export const getGetTenantEEConfigUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/ee-config`
}

/**
 * @summary 获取租户 EE 扩展配置（SuperAdmin）
 */
export const getTenantEEConfig = async (slug: string, options?: RequestInit): Promise<TenantEEConfigResp> => {

  return customFetch<TenantEEConfigResp>(getGetTenantEEConfigUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTenantEEConfigQueryKey = (slug: string,) => {
    return [
    `/v1/tenants/${slug}/ee-config`
    ] as const;
    }


export const getGetTenantEEConfigQueryOptions = <TData = Awaited<ReturnType<typeof getTenantEEConfig>>, TError = unknown>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantEEConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTenantEEConfigQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTenantEEConfig>>> = ({ signal }) => getTenantEEConfig(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTenantEEConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTenantEEConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getTenantEEConfig>>>
export type GetTenantEEConfigQueryError = unknown


export function useGetTenantEEConfig<TData = Awaited<ReturnType<typeof getTenantEEConfig>>, TError = unknown>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantEEConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTenantEEConfig>>,
          TError,
          Awaited<ReturnType<typeof getTenantEEConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTenantEEConfig<TData = Awaited<ReturnType<typeof getTenantEEConfig>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantEEConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTenantEEConfig>>,
          TError,
          Awaited<ReturnType<typeof getTenantEEConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTenantEEConfig<TData = Awaited<ReturnType<typeof getTenantEEConfig>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantEEConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取租户 EE 扩展配置（SuperAdmin）
 */

export function useGetTenantEEConfig<TData = Awaited<ReturnType<typeof getTenantEEConfig>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantEEConfig>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTenantEEConfigQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpsertTenantEEConfigUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/ee-config`
}

/**
 * @summary 更新租户 EE 扩展配置（SuperAdmin）
 */
export const upsertTenantEEConfig = async (slug: string,
    upsertTenantEEConfigBody: UpsertTenantEEConfigBody, options?: RequestInit): Promise<TenantEEConfigResp> => {

  return customFetch<TenantEEConfigResp>(getUpsertTenantEEConfigUrl(slug),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertTenantEEConfigBody)
  }
);}




export const getUpsertTenantEEConfigMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertTenantEEConfig>>, TError,{slug: string;data: UpsertTenantEEConfigBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertTenantEEConfig>>, TError,{slug: string;data: UpsertTenantEEConfigBody}, TContext> => {

const mutationKey = ['upsertTenantEEConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertTenantEEConfig>>, {slug: string;data: UpsertTenantEEConfigBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  upsertTenantEEConfig(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpsertTenantEEConfigMutationResult = NonNullable<Awaited<ReturnType<typeof upsertTenantEEConfig>>>
    export type UpsertTenantEEConfigMutationBody = UpsertTenantEEConfigBody
    export type UpsertTenantEEConfigMutationError = unknown

    /**
 * @summary 更新租户 EE 扩展配置（SuperAdmin）
 */
export const useUpsertTenantEEConfig = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertTenantEEConfig>>, TError,{slug: string;data: UpsertTenantEEConfigBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertTenantEEConfig>>,
        TError,
        {slug: string;data: UpsertTenantEEConfigBody},
        TContext
      > => {
      return useMutation(getUpsertTenantEEConfigMutationOptions(options), queryClient);
    }
