/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProjectAuthKey200,
  CreateProjectAuthKeyBody,
  CreateProjectBody,
  DeleteProject200,
  DeleteProjectAuthKey200,
  ExportOpenApi200,
  ExportOpenApiParams,
  GetProjectAuth200,
  ListProjectsParams,
  ProjectListResp,
  ProjectResp,
  UpdateProjectAuth200,
  UpdateProjectAuthBody,
  UpdateProjectBody
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListProjectsUrl = (slug: string,
    params?: ListProjectsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects?${stringifiedParams}` : `/v1/tenants/${slug}/projects`
}

/**
 * @summary 获取项目列表
 */
export const listProjects = async (slug: string,
    params?: ListProjectsParams, options?: RequestInit): Promise<ProjectListResp> => {

  return customFetch<ProjectListResp>(getListProjectsUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProjectsQueryKey = (slug: string,
    params?: ListProjectsParams,) => {
    return [
    `/v1/tenants/${slug}/projects`, ...(params ? [params] : [])
    ] as const;
    }


export const getListProjectsQueryOptions = <TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(slug: string,
    params?: ListProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProjectsQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjects>>> = ({ signal }) => listProjects(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listProjects>>>
export type ListProjectsQueryError = unknown


export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
 slug: string,
    params: undefined |  ListProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
 slug: string,
    params?: ListProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
 slug: string,
    params?: ListProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取项目列表
 */

export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
 slug: string,
    params?: ListProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProjectsQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateProjectUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/projects`
}

/**
 * @summary 创建项目
 */
export const createProject = async (slug: string,
    createProjectBody: CreateProjectBody, options?: RequestInit): Promise<ProjectResp> => {

  return customFetch<ProjectResp>(getCreateProjectUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProjectBody)
  }
);}




export const getCreateProjectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{slug: string;data: CreateProjectBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{slug: string;data: CreateProjectBody}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, {slug: string;data: CreateProjectBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  createProject(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = CreateProjectBody
    export type CreateProjectMutationError = unknown

    /**
 * @summary 创建项目
 */
export const useCreateProject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{slug: string;data: CreateProjectBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        {slug: string;data: CreateProjectBody},
        TContext
      > => {
      return useMutation(getCreateProjectMutationOptions(options), queryClient);
    }
    export const getGetProjectUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}`
}

/**
 * @summary 获取项目详情
 */
export const getProject = async (slug: string,
    projectId: number, options?: RequestInit): Promise<ProjectResp> => {

  return customFetch<ProjectResp>(getGetProjectUrl(slug,projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProjectQueryKey = (slug: string,
    projectId: number,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}`
    ] as const;
    }


export const getGetProjectQueryOptions = <TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(slug: string,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectQueryKey(slug,projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProject>>> = ({ signal }) => getProject(slug,projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectQueryResult = NonNullable<Awaited<ReturnType<typeof getProject>>>
export type GetProjectQueryError = unknown


export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(
 slug: string,
    projectId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(
 slug: string,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(
 slug: string,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取项目详情
 */

export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(
 slug: string,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectQueryOptions(slug,projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateProjectUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}`
}

/**
 * @summary 更新项目
 */
export const updateProject = async (slug: string,
    projectId: number,
    updateProjectBody: UpdateProjectBody, options?: RequestInit): Promise<ProjectResp> => {

  return customFetch<ProjectResp>(getUpdateProjectUrl(slug,projectId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProjectBody)
  }
);}




export const getUpdateProjectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{slug: string;projectId: number;data: UpdateProjectBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{slug: string;projectId: number;data: UpdateProjectBody}, TContext> => {

const mutationKey = ['updateProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProject>>, {slug: string;projectId: number;data: UpdateProjectBody}> = (props) => {
          const {slug,projectId,data} = props ?? {};

          return  updateProject(slug,projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>
    export type UpdateProjectMutationBody = UpdateProjectBody
    export type UpdateProjectMutationError = unknown

    /**
 * @summary 更新项目
 */
export const useUpdateProject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{slug: string;projectId: number;data: UpdateProjectBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProject>>,
        TError,
        {slug: string;projectId: number;data: UpdateProjectBody},
        TContext
      > => {
      return useMutation(getUpdateProjectMutationOptions(options), queryClient);
    }
    export const getDeleteProjectUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}`
}

/**
 * @summary 删除项目
 */
export const deleteProject = async (slug: string,
    projectId: number, options?: RequestInit): Promise<DeleteProject200> => {

  return customFetch<DeleteProject200>(getDeleteProjectUrl(slug,projectId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteProjectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{slug: string;projectId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{slug: string;projectId: number}, TContext> => {

const mutationKey = ['deleteProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProject>>, {slug: string;projectId: number}> = (props) => {
          const {slug,projectId} = props ?? {};

          return  deleteProject(slug,projectId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>

    export type DeleteProjectMutationError = unknown

    /**
 * @summary 删除项目
 */
export const useDeleteProject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{slug: string;projectId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProject>>,
        TError,
        {slug: string;projectId: number},
        TContext
      > => {
      return useMutation(getDeleteProjectMutationOptions(options), queryClient);
    }
    export const getGetProjectAuthUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/auth`
}

/**
 * @summary 获取项目访问控制配置
 */
export const getProjectAuth = async (slug: string,
    projectId: number, options?: RequestInit): Promise<GetProjectAuth200> => {

  return customFetch<GetProjectAuth200>(getGetProjectAuthUrl(slug,projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProjectAuthQueryKey = (slug: string,
    projectId: number,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}/auth`
    ] as const;
    }


export const getGetProjectAuthQueryOptions = <TData = Awaited<ReturnType<typeof getProjectAuth>>, TError = unknown>(slug: string,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectAuth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectAuthQueryKey(slug,projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectAuth>>> = ({ signal }) => getProjectAuth(slug,projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectAuth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectAuthQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectAuth>>>
export type GetProjectAuthQueryError = unknown


export function useGetProjectAuth<TData = Awaited<ReturnType<typeof getProjectAuth>>, TError = unknown>(
 slug: string,
    projectId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectAuth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectAuth>>,
          TError,
          Awaited<ReturnType<typeof getProjectAuth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectAuth<TData = Awaited<ReturnType<typeof getProjectAuth>>, TError = unknown>(
 slug: string,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectAuth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectAuth>>,
          TError,
          Awaited<ReturnType<typeof getProjectAuth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectAuth<TData = Awaited<ReturnType<typeof getProjectAuth>>, TError = unknown>(
 slug: string,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectAuth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取项目访问控制配置
 */

export function useGetProjectAuth<TData = Awaited<ReturnType<typeof getProjectAuth>>, TError = unknown>(
 slug: string,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectAuth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectAuthQueryOptions(slug,projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateProjectAuthUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/auth`
}

/**
 * @summary 切换项目访问控制方式
 */
export const updateProjectAuth = async (slug: string,
    projectId: number,
    updateProjectAuthBody: UpdateProjectAuthBody, options?: RequestInit): Promise<UpdateProjectAuth200> => {

  return customFetch<UpdateProjectAuth200>(getUpdateProjectAuthUrl(slug,projectId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProjectAuthBody)
  }
);}




export const getUpdateProjectAuthMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProjectAuth>>, TError,{slug: string;projectId: number;data: UpdateProjectAuthBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProjectAuth>>, TError,{slug: string;projectId: number;data: UpdateProjectAuthBody}, TContext> => {

const mutationKey = ['updateProjectAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProjectAuth>>, {slug: string;projectId: number;data: UpdateProjectAuthBody}> = (props) => {
          const {slug,projectId,data} = props ?? {};

          return  updateProjectAuth(slug,projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectAuthMutationResult = NonNullable<Awaited<ReturnType<typeof updateProjectAuth>>>
    export type UpdateProjectAuthMutationBody = UpdateProjectAuthBody
    export type UpdateProjectAuthMutationError = unknown

    /**
 * @summary 切换项目访问控制方式
 */
export const useUpdateProjectAuth = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProjectAuth>>, TError,{slug: string;projectId: number;data: UpdateProjectAuthBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProjectAuth>>,
        TError,
        {slug: string;projectId: number;data: UpdateProjectAuthBody},
        TContext
      > => {
      return useMutation(getUpdateProjectAuthMutationOptions(options), queryClient);
    }
    export const getCreateProjectAuthKeyUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/auth/keys`
}

/**
 * @summary 创建鉴权密钥（API Key 或 JWT 签名密钥）
 */
export const createProjectAuthKey = async (slug: string,
    projectId: number,
    createProjectAuthKeyBody: CreateProjectAuthKeyBody, options?: RequestInit): Promise<CreateProjectAuthKey200> => {

  return customFetch<CreateProjectAuthKey200>(getCreateProjectAuthKeyUrl(slug,projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProjectAuthKeyBody)
  }
);}




export const getCreateProjectAuthKeyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProjectAuthKey>>, TError,{slug: string;projectId: number;data: CreateProjectAuthKeyBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createProjectAuthKey>>, TError,{slug: string;projectId: number;data: CreateProjectAuthKeyBody}, TContext> => {

const mutationKey = ['createProjectAuthKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProjectAuthKey>>, {slug: string;projectId: number;data: CreateProjectAuthKeyBody}> = (props) => {
          const {slug,projectId,data} = props ?? {};

          return  createProjectAuthKey(slug,projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectAuthKeyMutationResult = NonNullable<Awaited<ReturnType<typeof createProjectAuthKey>>>
    export type CreateProjectAuthKeyMutationBody = CreateProjectAuthKeyBody
    export type CreateProjectAuthKeyMutationError = unknown

    /**
 * @summary 创建鉴权密钥（API Key 或 JWT 签名密钥）
 */
export const useCreateProjectAuthKey = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProjectAuthKey>>, TError,{slug: string;projectId: number;data: CreateProjectAuthKeyBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProjectAuthKey>>,
        TError,
        {slug: string;projectId: number;data: CreateProjectAuthKeyBody},
        TContext
      > => {
      return useMutation(getCreateProjectAuthKeyMutationOptions(options), queryClient);
    }
    export const getDeleteProjectAuthKeyUrl = (slug: string,
    projectId: number,
    keyId: string,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/auth/keys/${keyId}`
}

/**
 * @summary 删除鉴权密钥
 */
export const deleteProjectAuthKey = async (slug: string,
    projectId: number,
    keyId: string, options?: RequestInit): Promise<DeleteProjectAuthKey200> => {

  return customFetch<DeleteProjectAuthKey200>(getDeleteProjectAuthKeyUrl(slug,projectId,keyId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteProjectAuthKeyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProjectAuthKey>>, TError,{slug: string;projectId: number;keyId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProjectAuthKey>>, TError,{slug: string;projectId: number;keyId: string}, TContext> => {

const mutationKey = ['deleteProjectAuthKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProjectAuthKey>>, {slug: string;projectId: number;keyId: string}> = (props) => {
          const {slug,projectId,keyId} = props ?? {};

          return  deleteProjectAuthKey(slug,projectId,keyId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectAuthKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProjectAuthKey>>>

    export type DeleteProjectAuthKeyMutationError = unknown

    /**
 * @summary 删除鉴权密钥
 */
export const useDeleteProjectAuthKey = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProjectAuthKey>>, TError,{slug: string;projectId: number;keyId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProjectAuthKey>>,
        TError,
        {slug: string;projectId: number;keyId: string},
        TContext
      > => {
      return useMutation(getDeleteProjectAuthKeyMutationOptions(options), queryClient);
    }
    export const getExportOpenApiUrl = (slug: string,
    projectId: number,
    params?: ExportOpenApiParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/projects/${projectId}/openapi.json?${stringifiedParams}` : `/v1/tenants/${slug}/projects/${projectId}/openapi.json`
}

/**
 * @summary 导出项目 OpenAPI 规范
 */
export const exportOpenApi = async (slug: string,
    projectId: number,
    params?: ExportOpenApiParams, options?: RequestInit): Promise<ExportOpenApi200> => {

  return customFetch<ExportOpenApi200>(getExportOpenApiUrl(slug,projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getExportOpenApiQueryKey = (slug: string,
    projectId: number,
    params?: ExportOpenApiParams,) => {
    return [
    `/v1/tenants/${slug}/projects/${projectId}/openapi.json`, ...(params ? [params] : [])
    ] as const;
    }


export const getExportOpenApiQueryOptions = <TData = Awaited<ReturnType<typeof exportOpenApi>>, TError = unknown>(slug: string,
    projectId: number,
    params?: ExportOpenApiParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportOpenApi>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportOpenApiQueryKey(slug,projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportOpenApi>>> = ({ signal }) => exportOpenApi(slug,projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportOpenApi>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportOpenApiQueryResult = NonNullable<Awaited<ReturnType<typeof exportOpenApi>>>
export type ExportOpenApiQueryError = unknown


export function useExportOpenApi<TData = Awaited<ReturnType<typeof exportOpenApi>>, TError = unknown>(
 slug: string,
    projectId: number,
    params: undefined |  ExportOpenApiParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportOpenApi>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportOpenApi>>,
          TError,
          Awaited<ReturnType<typeof exportOpenApi>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportOpenApi<TData = Awaited<ReturnType<typeof exportOpenApi>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ExportOpenApiParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportOpenApi>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportOpenApi>>,
          TError,
          Awaited<ReturnType<typeof exportOpenApi>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportOpenApi<TData = Awaited<ReturnType<typeof exportOpenApi>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ExportOpenApiParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportOpenApi>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 导出项目 OpenAPI 规范
 */

export function useExportOpenApi<TData = Awaited<ReturnType<typeof exportOpenApi>>, TError = unknown>(
 slug: string,
    projectId: number,
    params?: ExportOpenApiParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportOpenApi>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportOpenApiQueryOptions(slug,projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






