/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetDatasourceSchema200,
  PreviewRow,
  PreviewTableParams,
  RunEndpoint200,
  RunEndpointBody,
  RunSQL200,
  RunSQLBody,
  TestQuery200,
  TestQueryBody
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetDatasourceSchemaUrl = (slug: string,
    datasourceId: number,) => {




  return `/v1/tenants/${slug}/datasources/${datasourceId}/schema`
}

/**
 * @summary 获取数据源表结构
 */
export const getDatasourceSchema = async (slug: string,
    datasourceId: number, options?: RequestInit): Promise<GetDatasourceSchema200> => {

  return customFetch<GetDatasourceSchema200>(getGetDatasourceSchemaUrl(slug,datasourceId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDatasourceSchemaQueryKey = (slug: string,
    datasourceId: number,) => {
    return [
    `/v1/tenants/${slug}/datasources/${datasourceId}/schema`
    ] as const;
    }


export const getGetDatasourceSchemaQueryOptions = <TData = Awaited<ReturnType<typeof getDatasourceSchema>>, TError = unknown>(slug: string,
    datasourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasourceSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDatasourceSchemaQueryKey(slug,datasourceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDatasourceSchema>>> = ({ signal }) => getDatasourceSchema(slug,datasourceId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && datasourceId !== null && datasourceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDatasourceSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDatasourceSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof getDatasourceSchema>>>
export type GetDatasourceSchemaQueryError = unknown


export function useGetDatasourceSchema<TData = Awaited<ReturnType<typeof getDatasourceSchema>>, TError = unknown>(
 slug: string,
    datasourceId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasourceSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDatasourceSchema>>,
          TError,
          Awaited<ReturnType<typeof getDatasourceSchema>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDatasourceSchema<TData = Awaited<ReturnType<typeof getDatasourceSchema>>, TError = unknown>(
 slug: string,
    datasourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasourceSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDatasourceSchema>>,
          TError,
          Awaited<ReturnType<typeof getDatasourceSchema>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDatasourceSchema<TData = Awaited<ReturnType<typeof getDatasourceSchema>>, TError = unknown>(
 slug: string,
    datasourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasourceSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取数据源表结构
 */

export function useGetDatasourceSchema<TData = Awaited<ReturnType<typeof getDatasourceSchema>>, TError = unknown>(
 slug: string,
    datasourceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDatasourceSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDatasourceSchemaQueryOptions(slug,datasourceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getPreviewTableUrl = (slug: string,
    datasourceId: number,
    table: string,
    params?: PreviewTableParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/datasources/${datasourceId}/tables/${table}/preview?${stringifiedParams}` : `/v1/tenants/${slug}/datasources/${datasourceId}/tables/${table}/preview`
}

/**
 * @summary 预览表数据
 */
export const previewTable = async (slug: string,
    datasourceId: number,
    table: string,
    params?: PreviewTableParams, options?: RequestInit): Promise<PreviewRow[]> => {

  return customFetch<PreviewRow[]>(getPreviewTableUrl(slug,datasourceId,table,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPreviewTableQueryKey = (slug: string,
    datasourceId: number,
    table: string,
    params?: PreviewTableParams,) => {
    return [
    `/v1/tenants/${slug}/datasources/${datasourceId}/tables/${table}/preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getPreviewTableQueryOptions = <TData = Awaited<ReturnType<typeof previewTable>>, TError = unknown>(slug: string,
    datasourceId: number,
    table: string,
    params?: PreviewTableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTable>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewTableQueryKey(slug,datasourceId,table,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewTable>>> = ({ signal }) => previewTable(slug,datasourceId,table,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && datasourceId !== null && datasourceId !== undefined && table !== null && table !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewTable>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PreviewTableQueryResult = NonNullable<Awaited<ReturnType<typeof previewTable>>>
export type PreviewTableQueryError = unknown


export function usePreviewTable<TData = Awaited<ReturnType<typeof previewTable>>, TError = unknown>(
 slug: string,
    datasourceId: number,
    table: string,
    params: undefined |  PreviewTableParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTable>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewTable>>,
          TError,
          Awaited<ReturnType<typeof previewTable>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewTable<TData = Awaited<ReturnType<typeof previewTable>>, TError = unknown>(
 slug: string,
    datasourceId: number,
    table: string,
    params?: PreviewTableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTable>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewTable>>,
          TError,
          Awaited<ReturnType<typeof previewTable>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewTable<TData = Awaited<ReturnType<typeof previewTable>>, TError = unknown>(
 slug: string,
    datasourceId: number,
    table: string,
    params?: PreviewTableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTable>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 预览表数据
 */

export function usePreviewTable<TData = Awaited<ReturnType<typeof previewTable>>, TError = unknown>(
 slug: string,
    datasourceId: number,
    table: string,
    params?: PreviewTableParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTable>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPreviewTableQueryOptions(slug,datasourceId,table,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getRunEndpointUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/run`
}

/**
 * @summary 代理执行 API 端点（含鉴权验证和访问日志）
 */
export const runEndpoint = async (slug: string,
    projectId: number,
    runEndpointBody: RunEndpointBody, options?: RequestInit): Promise<RunEndpoint200> => {

  return customFetch<RunEndpoint200>(getRunEndpointUrl(slug,projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(runEndpointBody)
  }
);}




export const getRunEndpointMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runEndpoint>>, TError,{slug: string;projectId: number;data: RunEndpointBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof runEndpoint>>, TError,{slug: string;projectId: number;data: RunEndpointBody}, TContext> => {

const mutationKey = ['runEndpoint'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runEndpoint>>, {slug: string;projectId: number;data: RunEndpointBody}> = (props) => {
          const {slug,projectId,data} = props ?? {};

          return  runEndpoint(slug,projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RunEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof runEndpoint>>>
    export type RunEndpointMutationBody = RunEndpointBody
    export type RunEndpointMutationError = unknown

    /**
 * @summary 代理执行 API 端点（含鉴权验证和访问日志）
 */
export const useRunEndpoint = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runEndpoint>>, TError,{slug: string;projectId: number;data: RunEndpointBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runEndpoint>>,
        TError,
        {slug: string;projectId: number;data: RunEndpointBody},
        TContext
      > => {
      return useMutation(getRunEndpointMutationOptions(options), queryClient);
    }
    export const getRunSQLUrl = (slug: string,
    projectId: number,) => {




  return `/v1/tenants/${slug}/projects/${projectId}/run-sql`
}

/**
 * @summary 直接执行 SQL（不保存，仅用于设计器调试）
 */
export const runSQL = async (slug: string,
    projectId: number,
    runSQLBody: RunSQLBody, options?: RequestInit): Promise<RunSQL200> => {

  return customFetch<RunSQL200>(getRunSQLUrl(slug,projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(runSQLBody)
  }
);}




export const getRunSQLMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runSQL>>, TError,{slug: string;projectId: number;data: RunSQLBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof runSQL>>, TError,{slug: string;projectId: number;data: RunSQLBody}, TContext> => {

const mutationKey = ['runSQL'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runSQL>>, {slug: string;projectId: number;data: RunSQLBody}> = (props) => {
          const {slug,projectId,data} = props ?? {};

          return  runSQL(slug,projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RunSQLMutationResult = NonNullable<Awaited<ReturnType<typeof runSQL>>>
    export type RunSQLMutationBody = RunSQLBody
    export type RunSQLMutationError = unknown

    /**
 * @summary 直接执行 SQL（不保存，仅用于设计器调试）
 */
export const useRunSQL = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runSQL>>, TError,{slug: string;projectId: number;data: RunSQLBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runSQL>>,
        TError,
        {slug: string;projectId: number;data: RunSQLBody},
        TContext
      > => {
      return useMutation(getRunSQLMutationOptions(options), queryClient);
    }
    export const getTestQueryUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/query/test`
}

/**
 * @summary 测试执行 API 端点（按指定 env 解析数据源）
 */
export const testQuery = async (slug: string,
    testQueryBody: TestQueryBody, options?: RequestInit): Promise<TestQuery200> => {

  return customFetch<TestQuery200>(getTestQueryUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(testQueryBody)
  }
);}




export const getTestQueryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testQuery>>, TError,{slug: string;data: TestQueryBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof testQuery>>, TError,{slug: string;data: TestQueryBody}, TContext> => {

const mutationKey = ['testQuery'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof testQuery>>, {slug: string;data: TestQueryBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  testQuery(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TestQueryMutationResult = NonNullable<Awaited<ReturnType<typeof testQuery>>>
    export type TestQueryMutationBody = TestQueryBody
    export type TestQueryMutationError = unknown

    /**
 * @summary 测试执行 API 端点（按指定 env 解析数据源）
 */
export const useTestQuery = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof testQuery>>, TError,{slug: string;data: TestQueryBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof testQuery>>,
        TError,
        {slug: string;data: TestQueryBody},
        TContext
      > => {
      return useMutation(getTestQueryMutationOptions(options), queryClient);
    }
