/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateScriptBody,
  DeleteScript200,
  ListScriptBuiltinsParams,
  ListScriptsParams,
  ScriptListResp,
  ScriptResp,
  UpdateScriptBody
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListScriptsUrl = (slug: string,
    params?: ListScriptsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/scripts?${stringifiedParams}` : `/v1/tenants/${slug}/scripts`
}

/**
 * @summary 获取脚本列表
 */
export const listScripts = async (slug: string,
    params?: ListScriptsParams, options?: RequestInit): Promise<ScriptListResp> => {

  return customFetch<ScriptListResp>(getListScriptsUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListScriptsQueryKey = (slug: string,
    params?: ListScriptsParams,) => {
    return [
    `/v1/tenants/${slug}/scripts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListScriptsQueryOptions = <TData = Awaited<ReturnType<typeof listScripts>>, TError = unknown>(slug: string,
    params?: ListScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScripts>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListScriptsQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listScripts>>> = ({ signal }) => listScripts(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listScripts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListScriptsQueryResult = NonNullable<Awaited<ReturnType<typeof listScripts>>>
export type ListScriptsQueryError = unknown


export function useListScripts<TData = Awaited<ReturnType<typeof listScripts>>, TError = unknown>(
 slug: string,
    params: undefined |  ListScriptsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScripts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listScripts>>,
          TError,
          Awaited<ReturnType<typeof listScripts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListScripts<TData = Awaited<ReturnType<typeof listScripts>>, TError = unknown>(
 slug: string,
    params?: ListScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScripts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listScripts>>,
          TError,
          Awaited<ReturnType<typeof listScripts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListScripts<TData = Awaited<ReturnType<typeof listScripts>>, TError = unknown>(
 slug: string,
    params?: ListScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScripts>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取脚本列表
 */

export function useListScripts<TData = Awaited<ReturnType<typeof listScripts>>, TError = unknown>(
 slug: string,
    params?: ListScriptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScripts>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListScriptsQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateScriptUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/scripts`
}

/**
 * @summary 创建脚本
 */
export const createScript = async (slug: string,
    createScriptBody: CreateScriptBody, options?: RequestInit): Promise<ScriptResp> => {

  return customFetch<ScriptResp>(getCreateScriptUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createScriptBody)
  }
);}




export const getCreateScriptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createScript>>, TError,{slug: string;data: CreateScriptBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createScript>>, TError,{slug: string;data: CreateScriptBody}, TContext> => {

const mutationKey = ['createScript'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createScript>>, {slug: string;data: CreateScriptBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  createScript(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateScriptMutationResult = NonNullable<Awaited<ReturnType<typeof createScript>>>
    export type CreateScriptMutationBody = CreateScriptBody
    export type CreateScriptMutationError = unknown

    /**
 * @summary 创建脚本
 */
export const useCreateScript = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createScript>>, TError,{slug: string;data: CreateScriptBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createScript>>,
        TError,
        {slug: string;data: CreateScriptBody},
        TContext
      > => {
      return useMutation(getCreateScriptMutationOptions(options), queryClient);
    }
    export const getListScriptBuiltinsUrl = (slug: string,
    params?: ListScriptBuiltinsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/scripts/builtins?${stringifiedParams}` : `/v1/tenants/${slug}/scripts/builtins`
}

/**
 * @summary 获取平台内置脚本（供「从内置添加」选择）
 */
export const listScriptBuiltins = async (slug: string,
    params?: ListScriptBuiltinsParams, options?: RequestInit): Promise<ScriptListResp> => {

  return customFetch<ScriptListResp>(getListScriptBuiltinsUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListScriptBuiltinsQueryKey = (slug: string,
    params?: ListScriptBuiltinsParams,) => {
    return [
    `/v1/tenants/${slug}/scripts/builtins`, ...(params ? [params] : [])
    ] as const;
    }


export const getListScriptBuiltinsQueryOptions = <TData = Awaited<ReturnType<typeof listScriptBuiltins>>, TError = unknown>(slug: string,
    params?: ListScriptBuiltinsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScriptBuiltins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListScriptBuiltinsQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listScriptBuiltins>>> = ({ signal }) => listScriptBuiltins(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listScriptBuiltins>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListScriptBuiltinsQueryResult = NonNullable<Awaited<ReturnType<typeof listScriptBuiltins>>>
export type ListScriptBuiltinsQueryError = unknown


export function useListScriptBuiltins<TData = Awaited<ReturnType<typeof listScriptBuiltins>>, TError = unknown>(
 slug: string,
    params: undefined |  ListScriptBuiltinsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScriptBuiltins>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listScriptBuiltins>>,
          TError,
          Awaited<ReturnType<typeof listScriptBuiltins>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListScriptBuiltins<TData = Awaited<ReturnType<typeof listScriptBuiltins>>, TError = unknown>(
 slug: string,
    params?: ListScriptBuiltinsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScriptBuiltins>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listScriptBuiltins>>,
          TError,
          Awaited<ReturnType<typeof listScriptBuiltins>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListScriptBuiltins<TData = Awaited<ReturnType<typeof listScriptBuiltins>>, TError = unknown>(
 slug: string,
    params?: ListScriptBuiltinsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScriptBuiltins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取平台内置脚本（供「从内置添加」选择）
 */

export function useListScriptBuiltins<TData = Awaited<ReturnType<typeof listScriptBuiltins>>, TError = unknown>(
 slug: string,
    params?: ListScriptBuiltinsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScriptBuiltins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListScriptBuiltinsQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCopyScriptFromBuiltinUrl = (slug: string,
    builtinId: number,) => {




  return `/v1/tenants/${slug}/scripts/builtins/${builtinId}/copy`
}

/**
 * @summary 从平台内置脚本复制一份到租户脚本库
 */
export const copyScriptFromBuiltin = async (slug: string,
    builtinId: number, options?: RequestInit): Promise<ScriptResp> => {

  return customFetch<ScriptResp>(getCopyScriptFromBuiltinUrl(slug,builtinId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getCopyScriptFromBuiltinMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof copyScriptFromBuiltin>>, TError,{slug: string;builtinId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof copyScriptFromBuiltin>>, TError,{slug: string;builtinId: number}, TContext> => {

const mutationKey = ['copyScriptFromBuiltin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof copyScriptFromBuiltin>>, {slug: string;builtinId: number}> = (props) => {
          const {slug,builtinId} = props ?? {};

          return  copyScriptFromBuiltin(slug,builtinId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CopyScriptFromBuiltinMutationResult = NonNullable<Awaited<ReturnType<typeof copyScriptFromBuiltin>>>

    export type CopyScriptFromBuiltinMutationError = unknown

    /**
 * @summary 从平台内置脚本复制一份到租户脚本库
 */
export const useCopyScriptFromBuiltin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof copyScriptFromBuiltin>>, TError,{slug: string;builtinId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof copyScriptFromBuiltin>>,
        TError,
        {slug: string;builtinId: number},
        TContext
      > => {
      return useMutation(getCopyScriptFromBuiltinMutationOptions(options), queryClient);
    }
    export const getUpdateScriptUrl = (slug: string,
    scriptId: number,) => {




  return `/v1/tenants/${slug}/scripts/${scriptId}`
}

/**
 * @summary 更新脚本
 */
export const updateScript = async (slug: string,
    scriptId: number,
    updateScriptBody?: UpdateScriptBody, options?: RequestInit): Promise<ScriptResp> => {

  return customFetch<ScriptResp>(getUpdateScriptUrl(slug,scriptId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateScriptBody)
  }
);}




export const getUpdateScriptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateScript>>, TError,{slug: string;scriptId: number;data?: UpdateScriptBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateScript>>, TError,{slug: string;scriptId: number;data?: UpdateScriptBody}, TContext> => {

const mutationKey = ['updateScript'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateScript>>, {slug: string;scriptId: number;data?: UpdateScriptBody}> = (props) => {
          const {slug,scriptId,data} = props ?? {};

          return  updateScript(slug,scriptId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateScriptMutationResult = NonNullable<Awaited<ReturnType<typeof updateScript>>>
    export type UpdateScriptMutationBody = UpdateScriptBody | undefined
    export type UpdateScriptMutationError = unknown

    /**
 * @summary 更新脚本
 */
export const useUpdateScript = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateScript>>, TError,{slug: string;scriptId: number;data?: UpdateScriptBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateScript>>,
        TError,
        {slug: string;scriptId: number;data?: UpdateScriptBody},
        TContext
      > => {
      return useMutation(getUpdateScriptMutationOptions(options), queryClient);
    }
    export const getDeleteScriptUrl = (slug: string,
    scriptId: number,) => {




  return `/v1/tenants/${slug}/scripts/${scriptId}`
}

/**
 * @summary 删除脚本
 */
export const deleteScript = async (slug: string,
    scriptId: number, options?: RequestInit): Promise<DeleteScript200> => {

  return customFetch<DeleteScript200>(getDeleteScriptUrl(slug,scriptId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteScriptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteScript>>, TError,{slug: string;scriptId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteScript>>, TError,{slug: string;scriptId: number}, TContext> => {

const mutationKey = ['deleteScript'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteScript>>, {slug: string;scriptId: number}> = (props) => {
          const {slug,scriptId} = props ?? {};

          return  deleteScript(slug,scriptId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteScriptMutationResult = NonNullable<Awaited<ReturnType<typeof deleteScript>>>

    export type DeleteScriptMutationError = unknown

    /**
 * @summary 删除脚本
 */
export const useDeleteScript = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteScript>>, TError,{slug: string;scriptId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteScript>>,
        TError,
        {slug: string;scriptId: number},
        TContext
      > => {
      return useMutation(getDeleteScriptMutationOptions(options), queryClient);
    }
