// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddUserData, AddUserResponses, CreateDataSourceData, CreateDataSourceResponses, CreateEndpointData, CreateEndpointResponses, CreateGatewayData, CreateGatewayResponses, CreateGroupData, CreateGroupResponses, CreateProjectData, CreateProjectResponses, CreateScriptData, CreateScriptResponses, CreateTenantData, CreateTenantResponses, DeleteDataSourceData, DeleteDataSourceResponses, DeleteEndpointData, DeleteEndpointResponses, DeleteGatewayData, DeleteGatewayResponses, DeleteGroupData, DeleteGroupResponses, DeleteProjectData, DeleteProjectResponses, DeleteScriptData, DeleteScriptResponses, DeleteTenantData, DeleteTenantResponses, ExportOpenApiData, ExportOpenApiResponses, GetDataSourceData, GetDataSourceResponses, GetGatewayData, GetGatewayResponses, GetProjectData, GetProjectResponses, GetTenantData, GetTenantResponses, ListDataSourcesData, ListDataSourcesResponses, ListEndpointsData, ListEndpointsResponses, ListGatewaysData, ListGatewaysResponses, ListGroupsData, ListGroupsResponses, ListProjectsData, ListProjectsResponses, ListScriptsData, ListScriptsResponses, ListTenantsData, ListTenantsResponses, ListUsersData, ListUsersResponses, LoginData, LoginResponses, MyTenantsData, MyTenantsResponses, RegisterData, RegisterResponses, RemoveUserData, RemoveUserResponses, TestQueryData, TestQueryResponses, UpdateDataSourceData, UpdateDataSourceResponses, UpdateEndpointData, UpdateEndpointResponses, UpdateGroupData, UpdateGroupResponses, UpdateProjectData, UpdateProjectResponses, UpdateScriptData, UpdateScriptResponses, UpdateTenantData, UpdateTenantResponses, UpdateUserRoleData, UpdateUserRoleResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 注册账号
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 登录
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 当前用户的租户列表
 */
export const myTenants = <ThrowOnError extends boolean = false>(options?: Options<MyTenantsData, ThrowOnError>) => (options?.client ?? client).get<MyTenantsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/my/tenants',
    ...options
});

/**
 * 租户列表 (SuperAdmin)
 */
export const listTenants = <ThrowOnError extends boolean = false>(options?: Options<ListTenantsData, ThrowOnError>) => (options?.client ?? client).get<ListTenantsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants',
    ...options
});

/**
 * 创建租户
 */
export const createTenant = <ThrowOnError extends boolean = false>(options: Options<CreateTenantData, ThrowOnError>) => (options.client ?? client).post<CreateTenantResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除租户
 */
export const deleteTenant = <ThrowOnError extends boolean = false>(options: Options<DeleteTenantData, ThrowOnError>) => (options.client ?? client).delete<DeleteTenantResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}',
    ...options
});

/**
 * 获取租户详情
 */
export const getTenant = <ThrowOnError extends boolean = false>(options: Options<GetTenantData, ThrowOnError>) => (options.client ?? client).get<GetTenantResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}',
    ...options
});

/**
 * 编辑租户
 */
export const updateTenant = <ThrowOnError extends boolean = false>(options: Options<UpdateTenantData, ThrowOnError>) => (options.client ?? client).put<UpdateTenantResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 用户列表
 */
export const listUsers = <ThrowOnError extends boolean = false>(options: Options<ListUsersData, ThrowOnError>) => (options.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/users',
    ...options
});

/**
 * 添加用户
 */
export const addUser = <ThrowOnError extends boolean = false>(options: Options<AddUserData, ThrowOnError>) => (options.client ?? client).post<AddUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 修改用户角色
 */
export const updateUserRole = <ThrowOnError extends boolean = false>(options: Options<UpdateUserRoleData, ThrowOnError>) => (options.client ?? client).put<UpdateUserRoleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/users/{userId}/role',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 移除用户
 */
export const removeUser = <ThrowOnError extends boolean = false>(options: Options<RemoveUserData, ThrowOnError>) => (options.client ?? client).delete<RemoveUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/users/{userId}',
    ...options
});

/**
 * 网关节点列表
 */
export const listGateways = <ThrowOnError extends boolean = false>(options: Options<ListGatewaysData, ThrowOnError>) => (options.client ?? client).get<ListGatewaysResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/gateways',
    ...options
});

/**
 * 创建网关节点
 */
export const createGateway = <ThrowOnError extends boolean = false>(options: Options<CreateGatewayData, ThrowOnError>) => (options.client ?? client).post<CreateGatewayResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/gateways',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除网关节点
 */
export const deleteGateway = <ThrowOnError extends boolean = false>(options: Options<DeleteGatewayData, ThrowOnError>) => (options.client ?? client).delete<DeleteGatewayResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/gateways/{gatewayId}',
    ...options
});

/**
 * 获取网关节点详情
 */
export const getGateway = <ThrowOnError extends boolean = false>(options: Options<GetGatewayData, ThrowOnError>) => (options.client ?? client).get<GetGatewayResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/gateways/{gatewayId}',
    ...options
});

/**
 * 数据源列表
 */
export const listDataSources = <ThrowOnError extends boolean = false>(options: Options<ListDataSourcesData, ThrowOnError>) => (options.client ?? client).get<ListDataSourcesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/datasources',
    ...options
});

/**
 * 创建数据源
 */
export const createDataSource = <ThrowOnError extends boolean = false>(options: Options<CreateDataSourceData, ThrowOnError>) => (options.client ?? client).post<CreateDataSourceResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/datasources',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除数据源
 */
export const deleteDataSource = <ThrowOnError extends boolean = false>(options: Options<DeleteDataSourceData, ThrowOnError>) => (options.client ?? client).delete<DeleteDataSourceResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/datasources/{datasourceId}',
    ...options
});

/**
 * 获取数据源详情
 */
export const getDataSource = <ThrowOnError extends boolean = false>(options: Options<GetDataSourceData, ThrowOnError>) => (options.client ?? client).get<GetDataSourceResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/datasources/{datasourceId}',
    ...options
});

/**
 * 编辑数据源
 */
export const updateDataSource = <ThrowOnError extends boolean = false>(options: Options<UpdateDataSourceData, ThrowOnError>) => (options.client ?? client).put<UpdateDataSourceResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/datasources/{datasourceId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 项目列表
 */
export const listProjects = <ThrowOnError extends boolean = false>(options: Options<ListProjectsData, ThrowOnError>) => (options.client ?? client).get<ListProjectsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects',
    ...options
});

/**
 * 创建项目
 */
export const createProject = <ThrowOnError extends boolean = false>(options: Options<CreateProjectData, ThrowOnError>) => (options.client ?? client).post<CreateProjectResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除项目
 */
export const deleteProject = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}',
    ...options
});

/**
 * 获取项目详情
 */
export const getProject = <ThrowOnError extends boolean = false>(options: Options<GetProjectData, ThrowOnError>) => (options.client ?? client).get<GetProjectResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}',
    ...options
});

/**
 * 编辑项目
 */
export const updateProject = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectData, ThrowOnError>) => (options.client ?? client).put<UpdateProjectResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 接口列表
 */
export const listEndpoints = <ThrowOnError extends boolean = false>(options: Options<ListEndpointsData, ThrowOnError>) => (options.client ?? client).get<ListEndpointsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/endpoints',
    ...options
});

/**
 * 创建接口
 */
export const createEndpoint = <ThrowOnError extends boolean = false>(options: Options<CreateEndpointData, ThrowOnError>) => (options.client ?? client).post<CreateEndpointResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/endpoints',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除接口
 */
export const deleteEndpoint = <ThrowOnError extends boolean = false>(options: Options<DeleteEndpointData, ThrowOnError>) => (options.client ?? client).delete<DeleteEndpointResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}',
    ...options
});

/**
 * 更新接口
 */
export const updateEndpoint = <ThrowOnError extends boolean = false>(options: Options<UpdateEndpointData, ThrowOnError>) => (options.client ?? client).put<UpdateEndpointResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 分组列表
 */
export const listGroups = <ThrowOnError extends boolean = false>(options: Options<ListGroupsData, ThrowOnError>) => (options.client ?? client).get<ListGroupsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/groups',
    ...options
});

/**
 * 创建分组
 */
export const createGroup = <ThrowOnError extends boolean = false>(options: Options<CreateGroupData, ThrowOnError>) => (options.client ?? client).post<CreateGroupResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/groups',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除分组
 */
export const deleteGroup = <ThrowOnError extends boolean = false>(options: Options<DeleteGroupData, ThrowOnError>) => (options.client ?? client).delete<DeleteGroupResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/groups/{groupId}',
    ...options
});

/**
 * 编辑分组
 */
export const updateGroup = <ThrowOnError extends boolean = false>(options: Options<UpdateGroupData, ThrowOnError>) => (options.client ?? client).put<UpdateGroupResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/groups/{groupId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 导出 OpenAPI文档
 */
export const exportOpenApi = <ThrowOnError extends boolean = false>(options: Options<ExportOpenApiData, ThrowOnError>) => (options.client ?? client).get<ExportOpenApiResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/projects/{projectId}/openapi.json',
    ...options
});

/**
 * 测试执行 SQL 查询
 */
export const testQuery = <ThrowOnError extends boolean = false>(options: Options<TestQueryData, ThrowOnError>) => (options.client ?? client).post<TestQueryResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/query/test',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 脚本列表
 */
export const listScripts = <ThrowOnError extends boolean = false>(options: Options<ListScriptsData, ThrowOnError>) => (options.client ?? client).get<ListScriptsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/scripts',
    ...options
});

/**
 * 创建脚本
 */
export const createScript = <ThrowOnError extends boolean = false>(options: Options<CreateScriptData, ThrowOnError>) => (options.client ?? client).post<CreateScriptResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/scripts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除脚本
 */
export const deleteScript = <ThrowOnError extends boolean = false>(options: Options<DeleteScriptData, ThrowOnError>) => (options.client ?? client).delete<DeleteScriptResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/scripts/{scriptId}',
    ...options
});

/**
 * 编辑脚本
 */
export const updateScript = <ThrowOnError extends boolean = false>(options: Options<UpdateScriptData, ThrowOnError>) => (options.client ?? client).put<UpdateScriptResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/{slug}/scripts/{scriptId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
