/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
export interface EndpointEnvActivity {
  env_id?: number;
  env_name?: string;
  version?: number;
  version_id?: number;
}

export interface ParamDef {
  default?: string;
  desc?: string;
  name?: string;
  required?: boolean;
  /** string, integer, number, boolean */
  type?: string;
}

export interface ScriptStep {
  code?: string;
  name?: string;
  script_id?: number;
  source?: string;
}

export interface ResponseDef {
  desc?: string;
  name?: string;
  /** string, integer, number, boolean */
  type?: string;
}

export interface APIEndpoint {
  created_at?: string;
  datasource_alias?: string;
  description?: string;
  /** per-env active version snapshot (one row per env where this endpoint is live) */
  env_activations?: EndpointEnvActivity[];
  group_id?: number;
  /** Derived/computed fields (not stored on the row itself): */
  has_draft?: boolean;
  id?: number;
  /** newest version number in endpoint_versions for this endpoint */
  latest_version?: number;
  method?: string;
  param_defs?: ParamDef[];
  path?: string;
  post_scripts?: ScriptStep[];
  /** PreScripts / PostScripts are ordered chains run sequentially around the SQL.
  Each step is either a reference to a reusable library script or inline code
  stored on the endpoint itself (see ScriptStep). In the pre-chain each stage's
  output params feed the next and any `{ error }` short-circuits; in the
  post-chain each stage's output becomes the next stage's `data`, and the last
  stage's output is the response body. */
  pre_scripts?: ScriptStep[];
  project_id?: number;
  response_defs?: ResponseDef[];
  sql?: string;
  summary?: string;
  tenant_id?: number;
  updated_at?: string;
}

export interface EndpointEnvActivityResp {
  env_id: number;
  env_name: string;
  version: number;
  version_id: number;
}

export interface ParamDefResp {
  default?: string;
  desc?: string;
  name: string;
  required: boolean;
  type: string;
}

export interface ScriptStepResp {
  code?: string;
  name?: string;
  script_id?: number;
  /** "library" | "inline" */
  source: string;
}

export interface ResponseDefResp {
  desc?: string;
  name: string;
  type: string;
}

export interface APIEndpointResp {
  created_at: string;
  datasource_alias: string;
  description?: string;
  env_activations?: EndpointEnvActivityResp[];
  group_id: number;
  has_draft: boolean;
  id: number;
  latest_version?: number;
  method: string;
  param_defs?: ParamDefResp[];
  path: string;
  post_scripts?: ScriptStepResp[];
  pre_scripts?: ScriptStepResp[];
  project_id: number;
  response_defs?: ResponseDefResp[];
  sql: string;
  summary: string;
  tenant_id: number;
  updated_at: string;
}

export interface PaginationInfo {
  is_pager: number;
  page: number;
  size: number;
  total: number;
}

export interface APIEndpointListResp {
  list: APIEndpointResp[];
  pagination: PaginationInfo;
}

export interface APIGroupResp {
  created_at: string;
  description?: string;
  id: number;
  name: string;
  project_id: number;
  tenant_id: number;
}

export interface APIGroupListResp {
  list: APIGroupResp[];
  pagination: PaginationInfo;
}

export interface ActivityEventResp {
  /** RFC3339 */
  at: string;
  desc: string;
  /** info / warning / error */
  severity: string;
  title: string;
  /** api / error / slow */
  type: string;
}

export interface ActivityListResp {
  list: ActivityEventResp[];
}

export interface TenantResp {
  avatar?: string;
  created_at: string;
  id: number;
  is_demo?: boolean;
  max_release_versions: number;
  name: string;
  slug: string;
  status: string;
  updated_at: string;
}

export interface UserResp {
  created_at: string;
  email: string;
  id: number;
  is_superadmin: boolean;
  name: string;
  updated_at: string;
}

export interface AuthResp {
  tenant?: TenantResp;
  tenants?: TenantResp[];
  token: string;
  user: UserResp;
}

export interface BindingResp {
  alias: string;
  datasource_id: number;
  env_id: number;
  tenant_id: number;
}

export interface DataSourceResp {
  created_at: string;
  dsn?: string;
  gateway_id: number;
  id: number;
  is_platform: boolean;
  name: string;
  tenant_id: number;
  type: string;
}

export interface DataSourceListResp {
  list: DataSourceResp[];
  pagination: PaginationInfo;
}

export interface DataSourceRefResp {
  alias: string;
}

export interface EndpointActivationLogResp {
  action: string;
  actor_id: number;
  actor_name?: string;
  at: string;
  endpoint_id: number;
  env_id?: number;
  env_name?: string;
  id: number;
  tenant_id: number;
  version?: number;
  version_id?: number;
}

export interface EndpointActivationLogListResp {
  list: EndpointActivationLogResp[];
  pagination: PaginationInfo;
}

export interface EndpointActiveVersionResp {
  activated_at: string;
  activated_by: number;
  endpoint_id: number;
  env_id: number;
  tenant_id: number;
  version: number;
  version_id: number;
}

export type EndpointCallLogRespBodyParams = {[key: string]: string};

export type EndpointCallLogRespHeaders = {[key: string]: string};

export type EndpointCallLogRespParams = { [key: string]: unknown };

export type EndpointCallLogRespPathParams = {[key: string]: string};

export type EndpointCallLogRespQueryParams = {[key: string]: string};

export interface EndpointCallLogResp {
  at: string;
  body_params?: EndpointCallLogRespBodyParams;
  endpoint_id: number;
  env_id?: number;
  env_name?: string;
  error?: string;
  headers?: EndpointCallLogRespHeaders;
  id: number;
  ip?: string;
  latency_ms: number;
  method: string;
  params?: EndpointCallLogRespParams;
  path: string;
  path_params?: EndpointCallLogRespPathParams;
  query_params?: EndpointCallLogRespQueryParams;
  status: number;
  tenant_id: number;
  user_agent?: string;
  version?: number;
  version_id?: number;
}

export interface EndpointCallLogListResp {
  list: EndpointCallLogResp[];
  pagination: PaginationInfo;
}

export interface ScriptSnapshotResp {
  code: string;
  id: number;
  name: string;
  type: string;
}

export interface EndpointVersionResp {
  created_at: string;
  created_by: number;
  datasource_ref?: DataSourceRefResp;
  endpoint_id: number;
  id: number;
  is_active: boolean;
  note: string;
  post_script_snapshots?: ScriptSnapshotResp[];
  pre_script_snapshots?: ScriptSnapshotResp[];
  snapshot?: APIEndpoint;
  snapshot_v: number;
  tenant_id: number;
  version: number;
}

export interface EndpointVersionListResp {
  list: EndpointVersionResp[];
  pagination: PaginationInfo;
}

export interface EnvironmentResp {
  created_at: string;
  id: number;
  is_default: boolean;
  name: string;
  project_id: number;
  tenant_id: number;
}

export interface GatewayResp {
  id: number;
  ip: string;
  is_platform: boolean;
  last_seen: string;
  name: string;
  status: string;
  tenant_id?: number;
  token?: string;
  version: string;
}

export interface GatewayListResp {
  list: GatewayResp[];
  pagination: PaginationInfo;
}

export interface HealthResp {
  /** "community" | "enterprise" */
  edition: string;
  /** EE 模式下 license 是否已通过校验 */
  is_licensed: boolean;
  /** "ok" */
  status: string;
}

export interface PlatformSettingsResp {
  allow_self_register: boolean;
  logo_url?: string;
  platform_name?: string;
  platform_tagline?: string;
}

export interface PreviewRow { [key: string]: unknown }

export interface ProjectResp {
  auth_type: string;
  avatar?: string;
  created_at: string;
  description: string;
  id: number;
  name: string;
  slug: string;
  tenant_id: number;
}

export interface ProjectListResp {
  list: ProjectResp[];
  pagination: PaginationInfo;
}

export interface ScriptResp {
  code: string;
  created_at: string;
  description?: string;
  id: number;
  is_platform: boolean;
  name: string;
  ref_count: number;
  tenant_id?: number;
  type: string;
}

export interface ScriptListResp {
  list: ScriptResp[];
  pagination: PaginationInfo;
}

export interface TenantListResp {
  list: TenantResp[];
  pagination: PaginationInfo;
}

export interface TenantUserResp {
  joined_at: string;
  role: string;
  tenant_id: number;
  user?: UserResp;
  user_id: number;
}

export interface TenantUserListResp {
  list: TenantUserResp[];
  pagination: PaginationInfo;
}

export interface TrafficBucketResp {
  /** 该桶错误数（status >= 400） */
  errors: number;
  /** 该桶总请求数 */
  total: number;
  /** 桶起始时刻（RFC3339, UTC） */
  ts: string;
}

export interface TrafficSeriesResp {
  /** hour / day */
  bucket: string;
  buckets: TrafficBucketResp[];
  /** 区间总错误数 */
  errors: number;
  /** 单桶峰值请求数 */
  peak: number;
  /** 24h / 7d / 30d */
  range: string;
  /** 区间总请求数 */
  total: number;
}

export interface ChangePasswordReq {
  /** @minLength 6 */
  new_password: string;
  old_password: string;
}

export type CreateDataSourceReqType = typeof CreateDataSourceReqType[keyof typeof CreateDataSourceReqType];


export const CreateDataSourceReqType = {
  mysql: 'mysql',
  postgres: 'postgres',
  sqlserver: 'sqlserver',
  starrocks: 'starrocks',
  doris: 'doris',
  sqlite: 'sqlite',
} as const;

export interface CreateDataSourceReq {
  dsn: string;
  gateway_id: number;
  name: string;
  type: CreateDataSourceReqType;
}

export interface CreateEnvReq {
  copy_bindings?: boolean;
  copy_from_env_id?: number;
  is_default?: boolean;
  name: string;
}

export interface RenameAliasReq {
  new_alias: string;
  old_alias: string;
}

export interface RenameEnvReq {
  name: string;
}

export type UpdateDataSourceReqType = typeof UpdateDataSourceReqType[keyof typeof UpdateDataSourceReqType];


export const UpdateDataSourceReqType = {
  mysql: 'mysql',
  postgres: 'postgres',
  sqlserver: 'sqlserver',
  starrocks: 'starrocks',
  doris: 'doris',
  sqlite: 'sqlite',
} as const;

export interface UpdateDataSourceReq {
  dsn?: string;
  gateway_id?: number;
  name?: string;
  type?: UpdateDataSourceReqType;
}

export interface UpsertBindingReq {
  alias: string;
  datasource_id: number;
}

export type ExecuteQueryBody = { [key: string]: unknown };

export type ExecuteQuery200 = { [key: string]: unknown };

export type ExecuteQueryPutBody = { [key: string]: unknown };

export type ExecuteQueryPut200 = { [key: string]: unknown };

export type ExecuteQueryPostBody = { [key: string]: unknown };

export type ExecuteQueryPost200 = { [key: string]: unknown };

export type ExecuteQueryDeleteBody = { [key: string]: unknown };

export type ExecuteQueryDelete200 = { [key: string]: unknown };

export type ChangePassword200 = {[key: string]: string};

export type LoginBody = {
  email?: string;
  password?: string;
};

export type RegisterBody = {
  email?: string;
  name?: string;
  password?: string;
  tenant_name?: string;
  tenant_slug?: string;
};

export type MyTenantsParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 是否分页，0=返回全部（默认1）
 */
is_pager?: number;
/**
 * 关键词搜索
 */
keyword?: string;
};

export type ListDataSourcesParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 是否分页，0=返回全部（默认1）
 */
is_pager?: number;
/**
 * 关键词搜索
 */
keyword?: string;
};

export type TestDatasourceBody = {
  dsn?: string;
  gateway_id?: number;
};

export type TestDatasource200Data = {
  latency_ms?: number;
};

export type TestDatasource200 = {
  data?: TestDatasource200Data;
};

export type DeleteDataSource200 = { [key: string]: unknown };

export type GetDatasourceSchema200DataItem = {
  columns?: unknown[];
  name?: string;
};

export type GetDatasourceSchema200 = {
  data?: GetDatasourceSchema200DataItem[];
};

export type PreviewTableParams = {
/**
 * 行数上限（默认100，最多500）
 */
limit?: number;
};

export type ListGatewaysParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 是否分页，0=返回全部（默认1）
 */
is_pager?: number;
/**
 * 关键词搜索
 */
keyword?: string;
};

export type CreateGatewayBody = {
  name?: string;
};

export type DeleteGateway200 = { [key: string]: unknown };

export type GetOverviewActivityParams = {
/**
 * 返回条数上限（默认 10，最大 50）
 */
limit?: number;
};

export type GetOverviewTrafficParams = {
/**
 * 时间范围：24h（默认，按小时分桶）/ 7d / 30d（按天分桶）
 */
range?: string;
};

export type ListProjectsParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 是否分页，0=返回全部（默认1）
 */
is_pager?: number;
/**
 * 关键词搜索
 */
keyword?: string;
};

export type CreateProjectBody = {
  datasource_id?: number;
  description?: string;
  env?: string;
  name?: string;
  slug?: string;
};

export type UpdateProjectBody = {
  description?: string;
  name?: string;
};

export type DeleteProject200 = { [key: string]: unknown };

export type RenameProjectAlias200 = { [key: string]: unknown };

export type GetProjectAuth200 = { [key: string]: unknown };

export type UpdateProjectAuthBody = {
  auth_type?: string;
};

export type UpdateProjectAuth200 = { [key: string]: unknown };

export type CreateProjectAuthKeyBody = {
  expires_at?: string;
  name?: string;
  type?: string;
};

export type CreateProjectAuthKey200 = { [key: string]: unknown };

export type DeleteProjectAuthKey200 = { [key: string]: unknown };

export type ListEndpointsParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 是否分页，0=返回全部（默认1）
 */
is_pager?: number;
/**
 * 关键词搜索
 */
keyword?: string;
/**
 * 按分组过滤（0=不过滤）
 */
group_id?: number;
};

export type CreateEndpointBody = {
  datasource_alias?: string;
  description?: string;
  group_id?: number;
  method?: string;
  param_defs?: unknown[];
  path?: string;
  post_scripts?: unknown[];
  pre_scripts?: unknown[];
  sql?: string;
  summary?: string;
};

export type UpdateEndpointBody = {
  datasource_alias?: string;
  description?: string;
  group_id?: number;
  method?: string;
  param_defs?: unknown[];
  path?: string;
  post_scripts?: unknown[];
  pre_scripts?: unknown[];
  response_defs?: unknown[];
  sql?: string;
  summary?: string;
};

export type DeleteEndpoint200 = { [key: string]: unknown };

export type PatchEndpointBody = {
  group_id?: number;
};

export type ListEndpointActivationLogParams = {
/**
 * 页码
 */
page?: number;
/**
 * 每页数量
 */
size?: number;
};

export type ListEndpointCallLogsParams = {
/**
 * 页码
 */
page?: number;
/**
 * 每页数量
 */
size?: number;
/**
 * 状态码段：all / 2xx / 4xx / 5xx
 */
status?: string;
/**
 * 关键词搜索（匹配 path 或 error）
 */
keyword?: string;
/**
 * 时间下限 (RFC3339)，仅返回该时间之后的
 */
since?: string;
};

export type PromoteEndpointVersionBody = {
  source_env_id?: number;
  target_env_id?: number;
};

export type PromoteEndpointVersion200 = { [key: string]: unknown };

export type PublishEndpointParams = {
/**
 * 环境名（默认为项目默认 env）
 */
env?: string;
/**
 * 环境ID（优先于 env）
 */
env_id?: number;
};

export type PublishEndpointBody = {
  note?: string;
};

export type RevertEndpointToActiveParams = {
/**
 * 环境名
 */
env?: string;
/**
 * 环境ID
 */
env_id?: number;
};

export type RevertEndpointToActive200 = { [key: string]: unknown };

export type UnpublishEndpointParams = {
/**
 * 环境名
 */
env?: string;
/**
 * 环境ID
 */
env_id?: number;
};

export type UnpublishEndpoint200 = { [key: string]: unknown };

export type ListEndpointVersionsParams = {
/**
 * 页码
 */
page?: number;
/**
 * 每页数量
 */
size?: number;
};

export type CreateEndpointVersionBody = {
  note?: string;
};

export type DeleteEndpointVersion200 = { [key: string]: unknown };

export type ActivateEndpointVersionParams = {
/**
 * 环境名
 */
env?: string;
/**
 * 环境ID
 */
env_id?: number;
};

export type ActivateEndpointVersion200 = { [key: string]: unknown };

export type RenameProjectEnvironment200 = { [key: string]: unknown };

export type DeleteProjectEnvironment200 = { [key: string]: unknown };

export type UpsertEnvBinding200 = { [key: string]: unknown };

export type DeleteEnvBinding200 = { [key: string]: unknown };

export type SetDefaultProjectEnvironment200 = { [key: string]: unknown };

export type ListGroupsParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 是否分页，0=返回全部（默认1）
 */
is_pager?: number;
/**
 * 关键词搜索
 */
keyword?: string;
};

export type CreateGroupBody = {
  description?: string;
  name?: string;
};

export type UpdateGroupBody = {
  description?: string;
  name?: string;
};

export type DeleteGroup200 = { [key: string]: unknown };

export type ExportOpenApiParams = {
/**
 * 环境名（默认: 项目默认 env）
 */
env?: string;
};

export type ExportOpenApi200 = { [key: string]: unknown };

export type RunEndpointBodyParams = { [key: string]: unknown };

export type RunEndpointBody = {
  auth_credential?: string;
  endpoint_id?: number;
  env_id?: number;
  ignore_scripts?: boolean;
  params?: RunEndpointBodyParams;
};

export type RunEndpoint200 = { [key: string]: unknown };

export type RunSQLBodyParams = { [key: string]: unknown };

export type RunSQLBody = {
  datasource_alias?: string;
  env_id?: number;
  params?: RunSQLBodyParams;
  sql?: string;
};

export type RunSQL200 = { [key: string]: unknown };

export type TestQueryBodyParams = { [key: string]: unknown };

export type TestQueryBody = {
  endpoint_id?: number;
  env_id?: number;
  ignore_scripts?: boolean;
  params?: TestQueryBodyParams;
};

export type TestQuery200 = { [key: string]: unknown };

export type ListScriptsParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 是否分页，0=返回全部（默认1）
 */
is_pager?: number;
/**
 * 关键词搜索
 */
keyword?: string;
};

export type CreateScriptBody = {
  code?: string;
  description?: string;
  name?: string;
  type?: string;
};

export type ListScriptBuiltinsParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 关键词搜索
 */
keyword?: string;
};

export type UpdateScriptBody = {
  code?: string;
  description?: string;
  name?: string;
  type?: string;
};

export type DeleteScript200 = { [key: string]: unknown };

export type UpdateTenantSettingsBody = {
  max_release_versions?: number;
};

export type ListUsersParams = {
/**
 * 页码（默认1）
 */
page?: number;
/**
 * 每页数量（默认10）
 */
size?: number;
/**
 * 是否分页，0=返回全部（默认1）
 */
is_pager?: number;
/**
 * 关键词搜索
 */
keyword?: string;
};

export type AddUserBody = {
  email?: string;
  name?: string;
  password?: string;
  role?: string;
};

export type AddUser200 = { [key: string]: unknown };

export type RemoveUser200 = { [key: string]: unknown };

export type UpdateUserRoleBody = {
  role?: string;
};

export type UpdateUserRole200 = { [key: string]: unknown };

