/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OwlApi Control Plane
 * 企业级 SQL to API 智能网关平台管理接口
 * OpenAPI spec version: 0.2.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddUser200,
  AddUserBody,
  ListUsersParams,
  RemoveUser200,
  TenantUserListResp,
  UpdateUserRole200,
  UpdateUserRoleBody
} from './sdk.schemas';

import { customFetch } from '../custom-fetch';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListUsersUrl = (slug: string,
    params?: ListUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/tenants/${slug}/users?${stringifiedParams}` : `/v1/tenants/${slug}/users`
}

/**
 * @summary 获取租户成员列表
 */
export const listUsers = async (slug: string,
    params?: ListUsersParams, options?: RequestInit): Promise<TenantUserListResp> => {

  return customFetch<TenantUserListResp>(getListUsersUrl(slug,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListUsersQueryKey = (slug: string,
    params?: ListUsersParams,) => {
    return [
    `/v1/tenants/${slug}/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(slug: string,
    params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersQueryKey(slug,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers(slug,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = unknown


export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
 slug: string,
    params: undefined |  ListUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
 slug: string,
    params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
 slug: string,
    params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取租户成员列表
 */

export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = unknown>(
 slug: string,
    params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersQueryOptions(slug,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getAddUserUrl = (slug: string,) => {




  return `/v1/tenants/${slug}/users`
}

/**
 * @summary 添加租户成员
 */
export const addUser = async (slug: string,
    addUserBody: AddUserBody, options?: RequestInit): Promise<AddUser200> => {

  return customFetch<AddUser200>(getAddUserUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addUserBody)
  }
);}




export const getAddUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addUser>>, TError,{slug: string;data: AddUserBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addUser>>, TError,{slug: string;data: AddUserBody}, TContext> => {

const mutationKey = ['addUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addUser>>, {slug: string;data: AddUserBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  addUser(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddUserMutationResult = NonNullable<Awaited<ReturnType<typeof addUser>>>
    export type AddUserMutationBody = AddUserBody
    export type AddUserMutationError = unknown

    /**
 * @summary 添加租户成员
 */
export const useAddUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addUser>>, TError,{slug: string;data: AddUserBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addUser>>,
        TError,
        {slug: string;data: AddUserBody},
        TContext
      > => {
      return useMutation(getAddUserMutationOptions(options), queryClient);
    }
    export const getRemoveUserUrl = (slug: string,
    userId: number,) => {




  return `/v1/tenants/${slug}/users/${userId}`
}

/**
 * @summary 移除租户成员
 */
export const removeUser = async (slug: string,
    userId: number, options?: RequestInit): Promise<RemoveUser200> => {

  return customFetch<RemoveUser200>(getRemoveUserUrl(slug,userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getRemoveUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUser>>, TError,{slug: string;userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeUser>>, TError,{slug: string;userId: number}, TContext> => {

const mutationKey = ['removeUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeUser>>, {slug: string;userId: number}> = (props) => {
          const {slug,userId} = props ?? {};

          return  removeUser(slug,userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveUserMutationResult = NonNullable<Awaited<ReturnType<typeof removeUser>>>

    export type RemoveUserMutationError = unknown

    /**
 * @summary 移除租户成员
 */
export const useRemoveUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeUser>>, TError,{slug: string;userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeUser>>,
        TError,
        {slug: string;userId: number},
        TContext
      > => {
      return useMutation(getRemoveUserMutationOptions(options), queryClient);
    }
    export const getUpdateUserRoleUrl = (slug: string,
    userId: number,) => {




  return `/v1/tenants/${slug}/users/${userId}/role`
}

/**
 * @summary 更新成员角色
 */
export const updateUserRole = async (slug: string,
    userId: number,
    updateUserRoleBody: UpdateUserRoleBody, options?: RequestInit): Promise<UpdateUserRole200> => {

  return customFetch<UpdateUserRole200>(getUpdateUserRoleUrl(slug,userId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserRoleBody)
  }
);}




export const getUpdateUserRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{slug: string;userId: number;data: UpdateUserRoleBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{slug: string;userId: number;data: UpdateUserRoleBody}, TContext> => {

const mutationKey = ['updateUserRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserRole>>, {slug: string;userId: number;data: UpdateUserRoleBody}> = (props) => {
          const {slug,userId,data} = props ?? {};

          return  updateUserRole(slug,userId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserRole>>>
    export type UpdateUserRoleMutationBody = UpdateUserRoleBody
    export type UpdateUserRoleMutationError = unknown

    /**
 * @summary 更新成员角色
 */
export const useUpdateUserRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{slug: string;userId: number;data: UpdateUserRoleBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserRole>>,
        TError,
        {slug: string;userId: number;data: UpdateUserRoleBody},
        TContext
      > => {
      return useMutation(getUpdateUserRoleMutationOptions(options), queryClient);
    }
