// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:3000/' | (string & {});
};

export type ApiEndpointListResp = {
    list?: Array<ApiEndpointResp>;
    pagination?: PaginationInfo;
};

export type ApiEndpointResp = {
    created_at?: string;
    datasource_id?: number;
    description?: string;
    group_id?: number;
    id?: number;
    methods?: Array<string>;
    param_defs?: Array<ParamDefResp>;
    params?: Array<string>;
    path?: string;
    post_script_id?: number;
    pre_script_id?: number;
    project_id?: number;
    sql?: string;
    summary?: string;
    tenant_id?: number;
};

export type ApiGroupListResp = {
    list?: Array<ApiGroupResp>;
    pagination?: PaginationInfo;
};

export type ApiGroupResp = {
    created_at?: string;
    description?: string;
    id?: number;
    name?: string;
    project_id?: number;
    tenant_id?: number;
};

export type AuthResp = {
    tenant?: TenantResp;
    tenants?: Array<TenantResp>;
    token?: string;
    user?: UserResp;
};

export type DataSourceEnvResp = {
    datasource_id?: number;
    dsn?: string;
    env?: string;
    gateway_id?: number;
    id?: number;
};

export type DataSourceListResp = {
    list?: Array<DataSourceResp>;
    pagination?: PaginationInfo;
};

export type DataSourceResp = {
    created_at?: string;
    envs?: Array<DataSourceEnvResp>;
    id?: number;
    is_dual?: boolean;
    name?: string;
    tenant_id?: number;
    type?: string;
};

export type GatewayListResp = {
    list?: Array<GatewayResp>;
    pagination?: PaginationInfo;
};

export type GatewayResp = {
    id?: number;
    ip?: string;
    last_seen?: string;
    name?: string;
    status?: string;
    tenant_id?: number;
    token?: string;
    version?: string;
};

export type PaginationInfo = {
    is_pager?: number;
    page?: number;
    size?: number;
    total?: number;
};

export type ParamDefResp = {
    default?: string;
    desc?: string;
    name?: string;
    required?: boolean;
    type?: string;
};

export type ProjectListResp = {
    list?: Array<ProjectResp>;
    pagination?: PaginationInfo;
};

export type ProjectResp = {
    created_at?: string;
    description?: string;
    id?: number;
    name?: string;
    tenant_id?: number;
};

export type R = {
    code?: number;
    data?: unknown;
    msg?: string;
};

export type RapiEndpoint = {
    code?: number;
    data?: ApiEndpointResp;
    msg?: string;
};

export type RapiEndpointList = {
    code?: number;
    data?: ApiEndpointListResp;
    msg?: string;
};

export type RapiGroup = {
    code?: number;
    data?: ApiGroupResp;
    msg?: string;
};

export type RapiGroupList = {
    code?: number;
    data?: ApiGroupListResp;
    msg?: string;
};

export type RAuth = {
    code?: number;
    data?: AuthResp;
    msg?: string;
};

export type RDataSource = {
    code?: number;
    data?: DataSourceResp;
    msg?: string;
};

export type RDataSourceList = {
    code?: number;
    data?: DataSourceListResp;
    msg?: string;
};

export type RGateway = {
    code?: number;
    data?: GatewayResp;
    msg?: string;
};

export type RGatewayList = {
    code?: number;
    data?: GatewayListResp;
    msg?: string;
};

export type RProject = {
    code?: number;
    data?: ProjectResp;
    msg?: string;
};

export type RProjectList = {
    code?: number;
    data?: ProjectListResp;
    msg?: string;
};

export type RScript = {
    code?: number;
    data?: ScriptResp;
    msg?: string;
};

export type RScriptList = {
    code?: number;
    data?: ScriptListResp;
    msg?: string;
};

export type RTenant = {
    code?: number;
    data?: TenantResp;
    msg?: string;
};

export type RTenantList = {
    code?: number;
    data?: TenantListResp;
    msg?: string;
};

export type RTenantUserList = {
    code?: number;
    data?: TenantUserListResp;
    msg?: string;
};

export type ScriptListResp = {
    list?: Array<ScriptResp>;
    pagination?: PaginationInfo;
};

export type ScriptResp = {
    code?: string;
    created_at?: string;
    description?: string;
    id?: number;
    name?: string;
    tenant_id?: number;
    type?: string;
};

export type TenantListResp = {
    list?: Array<TenantResp>;
    pagination?: PaginationInfo;
};

export type TenantResp = {
    created_at?: string;
    id?: number;
    name?: string;
    plan?: string;
    slug?: string;
    status?: string;
    updated_at?: string;
};

export type TenantUserListResp = {
    list?: Array<TenantUserResp>;
    pagination?: PaginationInfo;
};

export type TenantUserResp = {
    joined_at?: string;
    role?: string;
    tenant_id?: number;
    user?: UserResp;
    user_id?: number;
};

export type UserResp = {
    created_at?: string;
    email?: string;
    id?: number;
    is_superadmin?: boolean;
    name?: string;
    updated_at?: string;
};

export type ExecuteQueryData = {
    /**
     * 查询参数（由端点 param_defs 定义）
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * 租户 slug
         */
        slug: string;
        /**
         * API 路径
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/query/{path}';
};

export type ExecuteQueryResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExecuteQueryResponse = ExecuteQueryResponses[keyof ExecuteQueryResponses];

export type LoginData = {
    /**
     * 登录信息
     */
    body: {
        email?: string;
        password?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: RAuth;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
    /**
     * 注册信息
     */
    body: {
        email?: string;
        name?: string;
        password?: string;
        tenant_name?: string;
        tenant_slug?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: RAuth;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type MyTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/my/tenants';
};

export type MyTenantsResponses = {
    /**
     * OK
     */
    200: RTenantList;
};

export type MyTenantsResponse = MyTenantsResponses[keyof MyTenantsResponses];

export type ListAllTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants';
};

export type ListAllTenantsResponses = {
    /**
     * OK
     */
    200: RTenantList;
};

export type ListAllTenantsResponse = ListAllTenantsResponses[keyof ListAllTenantsResponses];

export type CreateTenantData = {
    /**
     * 租户信息
     */
    body: {
        name?: string;
        plan?: string;
        slug?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/tenants';
};

export type CreateTenantResponses = {
    /**
     * OK
     */
    200: RTenant;
};

export type CreateTenantResponse = CreateTenantResponses[keyof CreateTenantResponses];

export type DeleteTenantData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}';
};

export type DeleteTenantResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteTenantResponse = DeleteTenantResponses[keyof DeleteTenantResponses];

export type GetTenantData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}';
};

export type GetTenantResponses = {
    /**
     * OK
     */
    200: RTenant;
};

export type GetTenantResponse = GetTenantResponses[keyof GetTenantResponses];

export type UpdateTenantData = {
    /**
     * 更新信息
     */
    body: {
        name?: string;
        plan?: string;
        status?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}';
};

export type UpdateTenantResponses = {
    /**
     * OK
     */
    200: RTenant;
};

export type UpdateTenantResponse = UpdateTenantResponses[keyof UpdateTenantResponses];

export type ListDataSourcesData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/datasources';
};

export type ListDataSourcesResponses = {
    /**
     * OK
     */
    200: RDataSourceList;
};

export type ListDataSourcesResponse = ListDataSourcesResponses[keyof ListDataSourcesResponses];

export type CreateDataSourceData = {
    /**
     * 数据源信息
     */
    body: {
        envs?: Array<unknown>;
        is_dual?: boolean;
        name?: string;
        type?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources';
};

export type CreateDataSourceResponses = {
    /**
     * OK
     */
    200: RDataSource;
};

export type CreateDataSourceResponse = CreateDataSourceResponses[keyof CreateDataSourceResponses];

export type DeleteDataSourceData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 数据源ID
         */
        datasourceId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type DeleteDataSourceResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteDataSourceResponse = DeleteDataSourceResponses[keyof DeleteDataSourceResponses];

export type GetDataSourceData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 数据源ID
         */
        datasourceId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type GetDataSourceResponses = {
    /**
     * OK
     */
    200: RDataSource;
};

export type GetDataSourceResponse = GetDataSourceResponses[keyof GetDataSourceResponses];

export type UpdateDataSourceData = {
    /**
     * 更新信息
     */
    body?: {
        envs?: Array<unknown>;
        is_dual?: boolean;
        name?: string;
        type?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 数据源ID
         */
        datasourceId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type UpdateDataSourceResponses = {
    /**
     * OK
     */
    200: RDataSource;
};

export type UpdateDataSourceResponse = UpdateDataSourceResponses[keyof UpdateDataSourceResponses];

export type ListGatewaysData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/gateways';
};

export type ListGatewaysResponses = {
    /**
     * OK
     */
    200: RGatewayList;
};

export type ListGatewaysResponse = ListGatewaysResponses[keyof ListGatewaysResponses];

export type CreateGatewayData = {
    /**
     * 网关信息
     */
    body: {
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/gateways';
};

export type CreateGatewayResponses = {
    /**
     * OK
     */
    200: RGateway;
};

export type CreateGatewayResponse = CreateGatewayResponses[keyof CreateGatewayResponses];

export type DeleteGatewayData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 网关ID
         */
        gatewayId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/gateways/{gatewayId}';
};

export type DeleteGatewayResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteGatewayResponse = DeleteGatewayResponses[keyof DeleteGatewayResponses];

export type GetGatewayData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 网关ID
         */
        gatewayId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/gateways/{gatewayId}';
};

export type GetGatewayResponses = {
    /**
     * OK
     */
    200: RGateway;
};

export type GetGatewayResponse = GetGatewayResponses[keyof GetGatewayResponses];

export type ListProjectsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/projects';
};

export type ListProjectsResponses = {
    /**
     * OK
     */
    200: RProjectList;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    /**
     * 项目信息
     */
    body: {
        description?: string;
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects';
};

export type CreateProjectResponses = {
    /**
     * OK
     */
    200: RProject;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}';
};

export type DeleteProjectResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}';
};

export type GetProjectResponses = {
    /**
     * OK
     */
    200: RProject;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    /**
     * 更新信息
     */
    body: {
        description?: string;
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}';
};

export type UpdateProjectResponses = {
    /**
     * OK
     */
    200: RProject;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type ListEndpointsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints';
};

export type ListEndpointsResponses = {
    /**
     * OK
     */
    200: RapiEndpointList;
};

export type ListEndpointsResponse = ListEndpointsResponses[keyof ListEndpointsResponses];

export type CreateEndpointData = {
    /**
     * 端点信息
     */
    body: {
        datasource_id?: number;
        description?: string;
        group_id?: number;
        methods?: Array<unknown>;
        param_defs?: Array<unknown>;
        path?: string;
        post_script_id?: number;
        pre_script_id?: number;
        sql?: string;
        summary?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints';
};

export type CreateEndpointResponses = {
    /**
     * OK
     */
    200: RapiEndpoint;
};

export type CreateEndpointResponse = CreateEndpointResponses[keyof CreateEndpointResponses];

export type DeleteEndpointData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}';
};

export type DeleteEndpointResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteEndpointResponse = DeleteEndpointResponses[keyof DeleteEndpointResponses];

export type UpdateEndpointData = {
    /**
     * 更新信息
     */
    body?: {
        datasource_id?: number;
        description?: string;
        group_id?: number;
        methods?: Array<unknown>;
        param_defs?: Array<unknown>;
        path?: string;
        post_script_id?: number;
        pre_script_id?: number;
        sql?: string;
        summary?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}';
};

export type UpdateEndpointResponses = {
    /**
     * OK
     */
    200: RapiEndpoint;
};

export type UpdateEndpointResponse = UpdateEndpointResponses[keyof UpdateEndpointResponses];

export type ListGroupsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/groups';
};

export type ListGroupsResponses = {
    /**
     * OK
     */
    200: RapiGroupList;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    /**
     * 分组信息
     */
    body: {
        description?: string;
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/groups';
};

export type CreateGroupResponses = {
    /**
     * OK
     */
    200: RapiGroup;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 分组ID
         */
        groupId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/groups/{groupId}';
};

export type DeleteGroupResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type UpdateGroupData = {
    /**
     * 更新信息
     */
    body: {
        description?: string;
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 分组ID
         */
        groupId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/groups/{groupId}';
};

export type UpdateGroupResponses = {
    /**
     * OK
     */
    200: RapiGroup;
};

export type UpdateGroupResponse = UpdateGroupResponses[keyof UpdateGroupResponses];

export type ExportOpenApiData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/openapi.json';
};

export type ExportOpenApiResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExportOpenApiResponse = ExportOpenApiResponses[keyof ExportOpenApiResponses];

export type TestQueryData = {
    /**
     * 测试参数
     */
    body: {
        endpoint_id?: number;
        ignore_scripts?: boolean;
        params?: {
            [key: string]: unknown;
        };
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/query/test';
};

export type TestQueryResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type TestQueryResponse = TestQueryResponses[keyof TestQueryResponses];

export type ListScriptsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/scripts';
};

export type ListScriptsResponses = {
    /**
     * OK
     */
    200: RScriptList;
};

export type ListScriptsResponse = ListScriptsResponses[keyof ListScriptsResponses];

export type CreateScriptData = {
    /**
     * 脚本信息
     */
    body: {
        code?: string;
        description?: string;
        name?: string;
        type?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/scripts';
};

export type CreateScriptResponses = {
    /**
     * OK
     */
    200: RScript;
};

export type CreateScriptResponse = CreateScriptResponses[keyof CreateScriptResponses];

export type DeleteScriptData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 脚本ID
         */
        scriptId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/scripts/{scriptId}';
};

export type DeleteScriptResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteScriptResponse = DeleteScriptResponses[keyof DeleteScriptResponses];

export type UpdateScriptData = {
    /**
     * 更新信息
     */
    body?: {
        code?: string;
        description?: string;
        name?: string;
        type?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 脚本ID
         */
        scriptId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/scripts/{scriptId}';
};

export type UpdateScriptResponses = {
    /**
     * OK
     */
    200: RScript;
};

export type UpdateScriptResponse = UpdateScriptResponses[keyof UpdateScriptResponses];

export type ListUsersData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/users';
};

export type ListUsersResponses = {
    /**
     * OK
     */
    200: RTenantUserList;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type AddUserData = {
    /**
     * 成员信息
     */
    body: {
        email?: string;
        name?: string;
        password?: string;
        role?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/users';
};

export type AddUserResponses = {
    /**
     * OK
     */
    200: R;
};

export type AddUserResponse = AddUserResponses[keyof AddUserResponses];

export type RemoveUserData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 用户ID
         */
        userId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/users/{userId}';
};

export type RemoveUserResponses = {
    /**
     * OK
     */
    200: R;
};

export type RemoveUserResponse = RemoveUserResponses[keyof RemoveUserResponses];

export type UpdateUserRoleData = {
    /**
     * 角色
     */
    body: {
        role?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 用户ID
         */
        userId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/users/{userId}/role';
};

export type UpdateUserRoleResponses = {
    /**
     * OK
     */
    200: R;
};

export type UpdateUserRoleResponse = UpdateUserRoleResponses[keyof UpdateUserRoleResponses];
