// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:3000/' | (string & {});
};

export type ApiEndpoint = {
    created_at?: string;
    datasource_alias?: string;
    description?: string;
    /**
     * per-env active version snapshot (one row per env where this endpoint is live)
     */
    env_activations?: Array<EndpointEnvActivity>;
    group_id?: number;
    /**
     * Derived/computed fields (not stored on the row itself):
     */
    has_draft?: boolean;
    id?: number;
    /**
     * newest version number in endpoint_versions for this endpoint
     */
    latest_version?: number;
    methods?: Array<string>;
    param_defs?: Array<ParamDef>;
    params?: Array<string>;
    path?: string;
    post_script_id?: number;
    pre_script_id?: number;
    project_id?: number;
    sql?: string;
    summary?: string;
    tenant_id?: number;
    updated_at?: string;
};

export type EndpointEnvActivity = {
    env_id?: number;
    env_name?: string;
    version?: number;
    version_id?: number;
};

export type ParamDef = {
    default?: string;
    desc?: string;
    name?: string;
    required?: boolean;
    /**
     * string, integer, number, boolean
     */
    type?: string;
};

export type ApiEndpointListResp = {
    list: Array<ApiEndpointResp>;
    pagination: PaginationInfo;
};

export type ApiEndpointResp = {
    created_at: string;
    datasource_alias: string;
    description?: string;
    env_activations?: Array<EndpointEnvActivityResp>;
    group_id: number;
    has_draft: boolean;
    id: number;
    latest_version?: number;
    methods: Array<string>;
    param_defs?: Array<ParamDefResp>;
    params: Array<string>;
    path: string;
    post_script_id?: number;
    pre_script_id?: number;
    project_id: number;
    sql: string;
    summary: string;
    tenant_id: number;
    updated_at: string;
};

export type ApiGroupListResp = {
    list: Array<ApiGroupResp>;
    pagination: PaginationInfo;
};

export type ApiGroupResp = {
    created_at: string;
    description?: string;
    id: number;
    name: string;
    project_id: number;
    tenant_id: number;
};

export type AuthResp = {
    tenant?: TenantResp;
    tenants?: Array<TenantResp>;
    token: string;
    user: UserResp;
};

export type DataSourceListResp = {
    list: Array<DataSourceResp>;
    pagination: PaginationInfo;
};

export type DataSourceRefResp = {
    alias: string;
};

export type DataSourceResp = {
    created_at: string;
    dsn?: string;
    gateway_id: number;
    id: number;
    is_platform: boolean;
    name: string;
    tenant_id: number;
    type: string;
};

export type EndpointActivationLogListResp = {
    list: Array<EndpointActivationLogResp>;
    pagination: PaginationInfo;
};

export type EndpointActivationLogResp = {
    action: string;
    actor_id: number;
    actor_name?: string;
    at: string;
    endpoint_id: number;
    env_id?: number;
    env_name?: string;
    id: number;
    tenant_id: number;
    version?: number;
    version_id?: number;
};

export type EndpointCallLogListResp = {
    list: Array<EndpointCallLogResp>;
    pagination: PaginationInfo;
};

export type EndpointCallLogResp = {
    at: string;
    endpoint_id: number;
    env_id?: number;
    env_name?: string;
    error?: string;
    id: number;
    ip?: string;
    latency_ms: number;
    method: string;
    params?: {
        [key: string]: unknown;
    };
    path: string;
    status: number;
    tenant_id: number;
    user_agent?: string;
    version?: number;
    version_id?: number;
};

export type EndpointEnvActivityResp = {
    env_id: number;
    env_name: string;
    version: number;
    version_id: number;
};

export type EndpointVersionListResp = {
    list: Array<EndpointVersionResp>;
    pagination: PaginationInfo;
};

export type EndpointVersionResp = {
    created_at: string;
    created_by: number;
    datasource_ref?: DataSourceRefResp;
    endpoint_id: number;
    id: number;
    is_active: boolean;
    note: string;
    post_script_snapshot?: ScriptSnapshotResp;
    pre_script_snapshot?: ScriptSnapshotResp;
    snapshot?: ApiEndpoint;
    snapshot_v: number;
    tenant_id: number;
    version: number;
};

export type GatewayListResp = {
    list: Array<GatewayResp>;
    pagination: PaginationInfo;
};

export type GatewayResp = {
    id: number;
    ip: string;
    is_platform: boolean;
    last_seen: string;
    name: string;
    status: string;
    tenant_id?: number;
    token?: string;
    version: string;
};

export type HealthResp = {
    /**
     * "community" | "enterprise"
     */
    edition: string;
    /**
     * EE 模式下 license 是否已通过校验
     */
    is_licensed: boolean;
    /**
     * "ok"
     */
    status: string;
};

export type PaginationInfo = {
    is_pager: number;
    page: number;
    size: number;
    total: number;
};

export type ParamDefResp = {
    default?: string;
    desc?: string;
    name: string;
    required: boolean;
    type: string;
};

export type PlatformSettingsResp = {
    allow_self_register: boolean;
};

export type ProjectListResp = {
    list: Array<ProjectResp>;
    pagination: PaginationInfo;
};

export type ProjectResp = {
    avatar?: string;
    created_at: string;
    description: string;
    id: number;
    name: string;
    slug: string;
    tenant_id: number;
};

export type R = {
    code?: number;
    data?: unknown;
    msg?: string;
};

export type RapiEndpoint = {
    code: number;
    data: ApiEndpointResp;
    msg: string;
};

export type RapiEndpointList = {
    code: number;
    data: ApiEndpointListResp;
    msg: string;
};

export type RapiGroup = {
    code: number;
    data: ApiGroupResp;
    msg: string;
};

export type RapiGroupList = {
    code: number;
    data: ApiGroupListResp;
    msg: string;
};

export type RAuth = {
    code: number;
    data: AuthResp;
    msg: string;
};

export type RDataSource = {
    code: number;
    data: DataSourceResp;
    msg: string;
};

export type RDataSourceList = {
    code: number;
    data: DataSourceListResp;
    msg: string;
};

export type REndpointActivationLogList = {
    code: number;
    data: EndpointActivationLogListResp;
    msg: string;
};

export type REndpointCallLogList = {
    code: number;
    data: EndpointCallLogListResp;
    msg: string;
};

export type REndpointVersion = {
    code: number;
    data: EndpointVersionResp;
    msg: string;
};

export type REndpointVersionList = {
    code: number;
    data: EndpointVersionListResp;
    msg: string;
};

export type RGateway = {
    code: number;
    data: GatewayResp;
    msg: string;
};

export type RGatewayList = {
    code: number;
    data: GatewayListResp;
    msg: string;
};

export type RHealth = {
    code: number;
    data: HealthResp;
    msg: string;
};

export type RPlatformSettings = {
    code: number;
    data: PlatformSettingsResp;
    msg: string;
};

export type RProject = {
    code: number;
    data: ProjectResp;
    msg: string;
};

export type RProjectList = {
    code: number;
    data: ProjectListResp;
    msg: string;
};

export type RScript = {
    code: number;
    data: ScriptResp;
    msg: string;
};

export type RScriptList = {
    code: number;
    data: ScriptListResp;
    msg: string;
};

export type RTenant = {
    code: number;
    data: TenantResp;
    msg: string;
};

export type RTenantList = {
    code: number;
    data: TenantListResp;
    msg: string;
};

export type RTenantUserList = {
    code: number;
    data: TenantUserListResp;
    msg: string;
};

export type ScriptListResp = {
    list: Array<ScriptResp>;
    pagination: PaginationInfo;
};

export type ScriptResp = {
    code: string;
    created_at: string;
    description?: string;
    id: number;
    is_platform: boolean;
    name: string;
    tenant_id?: number;
    type: string;
};

export type ScriptSnapshotResp = {
    code: string;
    id: number;
    name: string;
    type: string;
};

export type TenantListResp = {
    list: Array<TenantResp>;
    pagination: PaginationInfo;
};

export type TenantResp = {
    avatar?: string;
    created_at: string;
    id: number;
    max_release_versions: number;
    name: string;
    plan: string;
    slug: string;
    status: string;
    updated_at: string;
};

export type TenantUserListResp = {
    list: Array<TenantUserResp>;
    pagination: PaginationInfo;
};

export type TenantUserResp = {
    joined_at: string;
    role: string;
    tenant_id: number;
    user?: UserResp;
    user_id: number;
};

export type UserResp = {
    created_at: string;
    email: string;
    id: number;
    is_superadmin: boolean;
    name: string;
    updated_at: string;
};

export type ChangePasswordReq = {
    new_password: string;
    old_password: string;
};

export type CreateDataSourceReq = {
    dsn: string;
    gateway_id: number;
    name: string;
    type: 'mysql' | 'postgres' | 'sqlserver' | 'starrocks' | 'doris' | 'sqlite';
};

export type CreateEnvReq = {
    copy_bindings?: boolean;
    copy_from_env_id?: number;
    is_default?: boolean;
    name: string;
};

export type RenameAliasReq = {
    new_alias: string;
    old_alias: string;
};

export type RenameEnvReq = {
    name: string;
};

export type UpdateDataSourceReq = {
    dsn?: string;
    gateway_id?: number;
    name?: string;
    type?: 'mysql' | 'postgres' | 'sqlserver' | 'starrocks' | 'doris' | 'sqlite';
};

export type UpsertBindingReq = {
    alias: string;
    datasource_id: number;
};

export type ExecuteQueryData = {
    /**
     * 请求参数 (POST/PUT 从 body 读，GET/DELETE 从 query string 读)
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * 环境名（项目级，例如 prod / dev / staging）
         */
        env: string;
        /**
         * 租户 slug
         */
        tenantSlug: string;
        /**
         * 项目 slug
         */
        projectSlug: string;
        /**
         * 接口路径（用户在项目中定义的路径）
         */
        path: string;
    };
    query?: never;
    url: '/-/{env}/{tenantSlug}/{projectSlug}/{path}';
};

export type ExecuteQueryResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExecuteQueryResponse = ExecuteQueryResponses[keyof ExecuteQueryResponses];

export type ExecuteQuery2Data = {
    /**
     * 请求参数 (POST/PUT 从 body 读，GET/DELETE 从 query string 读)
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * 环境名（项目级，例如 prod / dev / staging）
         */
        env: string;
        /**
         * 租户 slug
         */
        tenantSlug: string;
        /**
         * 项目 slug
         */
        projectSlug: string;
        /**
         * 接口路径（用户在项目中定义的路径）
         */
        path: string;
    };
    query?: never;
    url: '/-/{env}/{tenantSlug}/{projectSlug}/{path}';
};

export type ExecuteQuery2Responses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExecuteQuery2Response = ExecuteQuery2Responses[keyof ExecuteQuery2Responses];

export type ExecuteQuery3Data = {
    /**
     * 请求参数 (POST/PUT 从 body 读，GET/DELETE 从 query string 读)
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * 环境名（项目级，例如 prod / dev / staging）
         */
        env: string;
        /**
         * 租户 slug
         */
        tenantSlug: string;
        /**
         * 项目 slug
         */
        projectSlug: string;
        /**
         * 接口路径（用户在项目中定义的路径）
         */
        path: string;
    };
    query?: never;
    url: '/-/{env}/{tenantSlug}/{projectSlug}/{path}';
};

export type ExecuteQuery3Responses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExecuteQuery3Response = ExecuteQuery3Responses[keyof ExecuteQuery3Responses];

export type ExecuteQuery4Data = {
    /**
     * 请求参数 (POST/PUT 从 body 读，GET/DELETE 从 query string 读)
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * 环境名（项目级，例如 prod / dev / staging）
         */
        env: string;
        /**
         * 租户 slug
         */
        tenantSlug: string;
        /**
         * 项目 slug
         */
        projectSlug: string;
        /**
         * 接口路径（用户在项目中定义的路径）
         */
        path: string;
    };
    query?: never;
    url: '/-/{env}/{tenantSlug}/{projectSlug}/{path}';
};

export type ExecuteQuery4Responses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExecuteQuery4Response = ExecuteQuery4Responses[keyof ExecuteQuery4Responses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: RHealth;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ChangePasswordData = {
    /**
     * 密码信息
     */
    body: ChangePasswordReq;
    path?: never;
    query?: never;
    url: '/v1/auth/change-password';
};

export type ChangePasswordResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type LoginData = {
    /**
     * 登录信息
     */
    body: {
        email?: string;
        password?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: RAuth;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
    /**
     * 注册信息
     */
    body: {
        email?: string;
        name?: string;
        password?: string;
        tenant_name?: string;
        tenant_slug?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: RAuth;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type MyTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/my/tenants';
};

export type MyTenantsResponses = {
    /**
     * OK
     */
    200: RTenantList;
};

export type MyTenantsResponse = MyTenantsResponses[keyof MyTenantsResponses];

export type GetPlatformSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/platform/settings';
};

export type GetPlatformSettingsResponses = {
    /**
     * OK
     */
    200: RPlatformSettings;
};

export type GetPlatformSettingsResponse = GetPlatformSettingsResponses[keyof GetPlatformSettingsResponses];

export type UpdatePlatformSettingsData = {
    /**
     * 平台设置
     */
    body: {
        allow_self_register?: boolean;
    };
    path?: never;
    query?: never;
    url: '/v1/platform/settings';
};

export type UpdatePlatformSettingsResponses = {
    /**
     * OK
     */
    200: RPlatformSettings;
};

export type UpdatePlatformSettingsResponse = UpdatePlatformSettingsResponses[keyof UpdatePlatformSettingsResponses];

export type ListAllTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants';
};

export type ListAllTenantsResponses = {
    /**
     * OK
     */
    200: RTenantList;
};

export type ListAllTenantsResponse = ListAllTenantsResponses[keyof ListAllTenantsResponses];

export type CreateTenantData = {
    /**
     * 租户信息
     */
    body: {
        name?: string;
        plan?: string;
        slug?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/tenants';
};

export type CreateTenantResponses = {
    /**
     * OK
     */
    200: RTenant;
};

export type CreateTenantResponse = CreateTenantResponses[keyof CreateTenantResponses];

export type DeleteTenantData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}';
};

export type DeleteTenantResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteTenantResponse = DeleteTenantResponses[keyof DeleteTenantResponses];

export type GetTenantData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}';
};

export type GetTenantResponses = {
    /**
     * OK
     */
    200: RTenant;
};

export type GetTenantResponse = GetTenantResponses[keyof GetTenantResponses];

export type UpdateTenantData = {
    /**
     * 更新信息
     */
    body: {
        name?: string;
        plan?: string;
        status?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}';
};

export type UpdateTenantResponses = {
    /**
     * OK
     */
    200: RTenant;
};

export type UpdateTenantResponse = UpdateTenantResponses[keyof UpdateTenantResponses];

export type ListDataSourcesData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/datasources';
};

export type ListDataSourcesResponses = {
    /**
     * OK
     */
    200: RDataSourceList;
};

export type ListDataSourcesResponse = ListDataSourcesResponses[keyof ListDataSourcesResponses];

export type CreateDataSourceData = {
    /**
     * 数据源信息
     */
    body: CreateDataSourceReq;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources';
};

export type CreateDataSourceResponses = {
    /**
     * OK
     */
    200: RDataSource;
};

export type CreateDataSourceResponse = CreateDataSourceResponses[keyof CreateDataSourceResponses];

export type TestDatasourceData = {
    /**
     * 连接信息
     */
    body: {
        dsn?: string;
        gateway_id?: number;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources/test';
};

export type TestDatasourceResponses = {
    /**
     * OK
     */
    200: {
        data?: {
            latency_ms?: number;
        };
    };
};

export type TestDatasourceResponse = TestDatasourceResponses[keyof TestDatasourceResponses];

export type DeleteDataSourceData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 数据源ID
         */
        datasourceId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type DeleteDataSourceResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteDataSourceResponse = DeleteDataSourceResponses[keyof DeleteDataSourceResponses];

export type GetDataSourceData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 数据源ID
         */
        datasourceId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type GetDataSourceResponses = {
    /**
     * OK
     */
    200: RDataSource;
};

export type GetDataSourceResponse = GetDataSourceResponses[keyof GetDataSourceResponses];

export type UpdateDataSourceData = {
    /**
     * 更新信息
     */
    body?: UpdateDataSourceReq;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 数据源ID
         */
        datasourceId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type UpdateDataSourceResponses = {
    /**
     * OK
     */
    200: RDataSource;
};

export type UpdateDataSourceResponse = UpdateDataSourceResponses[keyof UpdateDataSourceResponses];

export type GetDatasourceSchemaData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 数据源ID
         */
        datasourceId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/datasources/{datasourceId}/schema';
};

export type GetDatasourceSchemaResponses = {
    /**
     * OK
     */
    200: {
        data?: Array<{
            columns?: Array<unknown>;
            name?: string;
        }>;
    };
};

export type GetDatasourceSchemaResponse = GetDatasourceSchemaResponses[keyof GetDatasourceSchemaResponses];

export type PreviewTableData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 数据源ID
         */
        datasourceId: number;
        /**
         * 表名
         */
        table: string;
    };
    query?: {
        /**
         * 行数上限（默认100，最多500）
         */
        limit?: number;
    };
    url: '/v1/tenants/{slug}/datasources/{datasourceId}/tables/{table}/preview';
};

export type PreviewTableResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type PreviewTableResponse = PreviewTableResponses[keyof PreviewTableResponses];

export type ListGatewaysData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/gateways';
};

export type ListGatewaysResponses = {
    /**
     * OK
     */
    200: RGatewayList;
};

export type ListGatewaysResponse = ListGatewaysResponses[keyof ListGatewaysResponses];

export type CreateGatewayData = {
    /**
     * 网关信息
     */
    body: {
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/gateways';
};

export type CreateGatewayResponses = {
    /**
     * OK
     */
    200: RGateway;
};

export type CreateGatewayResponse = CreateGatewayResponses[keyof CreateGatewayResponses];

export type DeleteGatewayData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 网关ID
         */
        gatewayId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/gateways/{gatewayId}';
};

export type DeleteGatewayResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteGatewayResponse = DeleteGatewayResponses[keyof DeleteGatewayResponses];

export type GetGatewayData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 网关ID
         */
        gatewayId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/gateways/{gatewayId}';
};

export type GetGatewayResponses = {
    /**
     * OK
     */
    200: RGateway;
};

export type GetGatewayResponse = GetGatewayResponses[keyof GetGatewayResponses];

export type ListProjectsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/projects';
};

export type ListProjectsResponses = {
    /**
     * OK
     */
    200: RProjectList;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    /**
     * 项目信息
     */
    body: {
        description?: string;
        name?: string;
        slug?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects';
};

export type CreateProjectResponses = {
    /**
     * OK
     */
    200: RProject;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}';
};

export type DeleteProjectResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}';
};

export type GetProjectResponses = {
    /**
     * OK
     */
    200: RProject;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    /**
     * 更新信息
     */
    body: {
        description?: string;
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}';
};

export type UpdateProjectResponses = {
    /**
     * OK
     */
    200: RProject;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type RenameProjectAliasData = {
    /**
     * old/new alias
     */
    body: RenameAliasReq;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/aliases/rename';
};

export type RenameProjectAliasResponses = {
    /**
     * OK
     */
    200: R;
};

export type RenameProjectAliasResponse = RenameProjectAliasResponses[keyof RenameProjectAliasResponses];

export type ListProjectBindingsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/bindings';
};

export type ListProjectBindingsResponses = {
    /**
     * OK
     */
    200: R;
};

export type ListProjectBindingsResponse = ListProjectBindingsResponses[keyof ListProjectBindingsResponses];

export type ListEndpointsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints';
};

export type ListEndpointsResponses = {
    /**
     * OK
     */
    200: RapiEndpointList;
};

export type ListEndpointsResponse = ListEndpointsResponses[keyof ListEndpointsResponses];

export type CreateEndpointData = {
    /**
     * 端点信息
     */
    body: {
        datasource_alias?: string;
        description?: string;
        group_id?: number;
        methods?: Array<unknown>;
        param_defs?: Array<unknown>;
        path?: string;
        post_script_id?: number;
        pre_script_id?: number;
        sql?: string;
        summary?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints';
};

export type CreateEndpointResponses = {
    /**
     * OK
     */
    200: RapiEndpoint;
};

export type CreateEndpointResponse = CreateEndpointResponses[keyof CreateEndpointResponses];

export type DeleteEndpointData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}';
};

export type DeleteEndpointResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteEndpointResponse = DeleteEndpointResponses[keyof DeleteEndpointResponses];

export type UpdateEndpointData = {
    /**
     * 更新信息
     */
    body?: {
        datasource_alias?: string;
        description?: string;
        group_id?: number;
        methods?: Array<unknown>;
        param_defs?: Array<unknown>;
        path?: string;
        post_script_id?: number;
        pre_script_id?: number;
        sql?: string;
        summary?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}';
};

export type UpdateEndpointResponses = {
    /**
     * OK
     */
    200: RapiEndpoint;
};

export type UpdateEndpointResponse = UpdateEndpointResponses[keyof UpdateEndpointResponses];

export type ListEndpointActivationLogData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        size?: number;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/activation-log';
};

export type ListEndpointActivationLogResponses = {
    /**
     * OK
     */
    200: REndpointActivationLogList;
};

export type ListEndpointActivationLogResponse = ListEndpointActivationLogResponses[keyof ListEndpointActivationLogResponses];

export type ListEndpointActivesData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/actives';
};

export type ListEndpointActivesResponses = {
    /**
     * OK
     */
    200: R;
};

export type ListEndpointActivesResponse = ListEndpointActivesResponses[keyof ListEndpointActivesResponses];

export type ListEndpointCallLogsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        size?: number;
        /**
         * 状态码段：all / 2xx / 4xx / 5xx
         */
        status?: string;
        /**
         * 关键词搜索（匹配 path 或 error）
         */
        keyword?: string;
        /**
         * 时间下限 (RFC3339)，仅返回该时间之后的
         */
        since?: string;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/call-logs';
};

export type ListEndpointCallLogsResponses = {
    /**
     * OK
     */
    200: REndpointCallLogList;
};

export type ListEndpointCallLogsResponse = ListEndpointCallLogsResponses[keyof ListEndpointCallLogsResponses];

export type PromoteEndpointVersionData = {
    /**
     * promote 参数
     */
    body: {
        source_env_id?: number;
        target_env_id?: number;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/promote';
};

export type PromoteEndpointVersionResponses = {
    /**
     * OK
     */
    200: R;
};

export type PromoteEndpointVersionResponse = PromoteEndpointVersionResponses[keyof PromoteEndpointVersionResponses];

export type PublishEndpointData = {
    /**
     * 版本说明
     */
    body?: {
        note?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: {
        /**
         * 环境名（默认为项目默认 env）
         */
        env?: string;
        /**
         * 环境ID（优先于 env）
         */
        env_id?: number;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/publish';
};

export type PublishEndpointResponses = {
    /**
     * OK
     */
    200: REndpointVersion;
};

export type PublishEndpointResponse = PublishEndpointResponses[keyof PublishEndpointResponses];

export type RevertEndpointToActiveData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: {
        /**
         * 环境名
         */
        env?: string;
        /**
         * 环境ID
         */
        env_id?: number;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/revert';
};

export type RevertEndpointToActiveResponses = {
    /**
     * OK
     */
    200: R;
};

export type RevertEndpointToActiveResponse = RevertEndpointToActiveResponses[keyof RevertEndpointToActiveResponses];

export type UnpublishEndpointData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: {
        /**
         * 环境名
         */
        env?: string;
        /**
         * 环境ID
         */
        env_id?: number;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/unpublish';
};

export type UnpublishEndpointResponses = {
    /**
     * OK
     */
    200: R;
};

export type UnpublishEndpointResponse = UnpublishEndpointResponses[keyof UnpublishEndpointResponses];

export type ListEndpointVersionsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        size?: number;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/versions';
};

export type ListEndpointVersionsResponses = {
    /**
     * OK
     */
    200: REndpointVersionList;
};

export type ListEndpointVersionsResponse = ListEndpointVersionsResponses[keyof ListEndpointVersionsResponses];

export type CreateEndpointVersionData = {
    /**
     * 版本说明
     */
    body?: {
        note?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/versions';
};

export type CreateEndpointVersionResponses = {
    /**
     * OK
     */
    200: REndpointVersion;
};

export type CreateEndpointVersionResponse = CreateEndpointVersionResponses[keyof CreateEndpointVersionResponses];

export type DeleteEndpointVersionData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
        /**
         * 版本ID
         */
        versionId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/versions/{versionId}';
};

export type DeleteEndpointVersionResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteEndpointVersionResponse = DeleteEndpointVersionResponses[keyof DeleteEndpointVersionResponses];

export type ActivateEndpointVersionData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 端点ID
         */
        endpointId: number;
        /**
         * 版本ID
         */
        versionId: number;
    };
    query?: {
        /**
         * 环境名
         */
        env?: string;
        /**
         * 环境ID
         */
        env_id?: number;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}/versions/{versionId}/activate';
};

export type ActivateEndpointVersionResponses = {
    /**
     * OK
     */
    200: R;
};

export type ActivateEndpointVersionResponse = ActivateEndpointVersionResponses[keyof ActivateEndpointVersionResponses];

export type ListProjectEnvironmentsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/environments';
};

export type ListProjectEnvironmentsResponses = {
    /**
     * OK
     */
    200: R;
};

export type ListProjectEnvironmentsResponse = ListProjectEnvironmentsResponses[keyof ListProjectEnvironmentsResponses];

export type CreateProjectEnvironmentData = {
    /**
     * 环境信息
     */
    body: CreateEnvReq;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/environments';
};

export type CreateProjectEnvironmentResponses = {
    /**
     * OK
     */
    200: R;
};

export type CreateProjectEnvironmentResponse = CreateProjectEnvironmentResponses[keyof CreateProjectEnvironmentResponses];

export type DeleteProjectEnvironmentData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 环境ID
         */
        envId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/environments/{envId}';
};

export type DeleteProjectEnvironmentResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteProjectEnvironmentResponse = DeleteProjectEnvironmentResponses[keyof DeleteProjectEnvironmentResponses];

export type RenameProjectEnvironmentData = {
    /**
     * 新名称
     */
    body: RenameEnvReq;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 环境ID
         */
        envId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/environments/{envId}';
};

export type RenameProjectEnvironmentResponses = {
    /**
     * OK
     */
    200: R;
};

export type RenameProjectEnvironmentResponse = RenameProjectEnvironmentResponses[keyof RenameProjectEnvironmentResponses];

export type ListEnvBindingsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 环境ID
         */
        envId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/environments/{envId}/bindings';
};

export type ListEnvBindingsResponses = {
    /**
     * OK
     */
    200: R;
};

export type ListEnvBindingsResponse = ListEnvBindingsResponses[keyof ListEnvBindingsResponses];

export type UpsertEnvBindingData = {
    /**
     * binding
     */
    body: UpsertBindingReq;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 环境ID
         */
        envId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/environments/{envId}/bindings';
};

export type UpsertEnvBindingResponses = {
    /**
     * OK
     */
    200: R;
};

export type UpsertEnvBindingResponse = UpsertEnvBindingResponses[keyof UpsertEnvBindingResponses];

export type DeleteEnvBindingData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 环境ID
         */
        envId: number;
        /**
         * 别名
         */
        alias: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/environments/{envId}/bindings/{alias}';
};

export type DeleteEnvBindingResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteEnvBindingResponse = DeleteEnvBindingResponses[keyof DeleteEnvBindingResponses];

export type SetDefaultProjectEnvironmentData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 环境ID
         */
        envId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/environments/{envId}/default';
};

export type SetDefaultProjectEnvironmentResponses = {
    /**
     * OK
     */
    200: R;
};

export type SetDefaultProjectEnvironmentResponse = SetDefaultProjectEnvironmentResponses[keyof SetDefaultProjectEnvironmentResponses];

export type ListGroupsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/groups';
};

export type ListGroupsResponses = {
    /**
     * OK
     */
    200: RapiGroupList;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    /**
     * 分组信息
     */
    body: {
        description?: string;
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/groups';
};

export type CreateGroupResponses = {
    /**
     * OK
     */
    200: RapiGroup;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 分组ID
         */
        groupId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/groups/{groupId}';
};

export type DeleteGroupResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type UpdateGroupData = {
    /**
     * 更新信息
     */
    body: {
        description?: string;
        name?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
        /**
         * 分组ID
         */
        groupId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/projects/{projectId}/groups/{groupId}';
};

export type UpdateGroupResponses = {
    /**
     * OK
     */
    200: RapiGroup;
};

export type UpdateGroupResponse = UpdateGroupResponses[keyof UpdateGroupResponses];

export type ExportOpenApiData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 项目ID
         */
        projectId: number;
    };
    query?: {
        /**
         * 环境名（默认: 项目默认 env）
         */
        env?: string;
    };
    url: '/v1/tenants/{slug}/projects/{projectId}/openapi.json';
};

export type ExportOpenApiResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExportOpenApiResponse = ExportOpenApiResponses[keyof ExportOpenApiResponses];

export type TestQueryData = {
    /**
     * 测试参数
     */
    body: {
        endpoint_id?: number;
        env_id?: number;
        ignore_scripts?: boolean;
        params?: {
            [key: string]: unknown;
        };
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/query/test';
};

export type TestQueryResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type TestQueryResponse = TestQueryResponses[keyof TestQueryResponses];

export type ListScriptsData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/scripts';
};

export type ListScriptsResponses = {
    /**
     * OK
     */
    200: RScriptList;
};

export type ListScriptsResponse = ListScriptsResponses[keyof ListScriptsResponses];

export type CreateScriptData = {
    /**
     * 脚本信息
     */
    body: {
        code?: string;
        description?: string;
        name?: string;
        type?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/scripts';
};

export type CreateScriptResponses = {
    /**
     * OK
     */
    200: RScript;
};

export type CreateScriptResponse = CreateScriptResponses[keyof CreateScriptResponses];

export type DeleteScriptData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 脚本ID
         */
        scriptId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/scripts/{scriptId}';
};

export type DeleteScriptResponses = {
    /**
     * OK
     */
    200: R;
};

export type DeleteScriptResponse = DeleteScriptResponses[keyof DeleteScriptResponses];

export type UpdateScriptData = {
    /**
     * 更新信息
     */
    body?: {
        code?: string;
        description?: string;
        name?: string;
        type?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 脚本ID
         */
        scriptId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/scripts/{scriptId}';
};

export type UpdateScriptResponses = {
    /**
     * OK
     */
    200: RScript;
};

export type UpdateScriptResponse = UpdateScriptResponses[keyof UpdateScriptResponses];

export type UpdateTenantSettingsData = {
    /**
     * 配置项
     */
    body: {
        max_release_versions?: number;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/settings';
};

export type UpdateTenantSettingsResponses = {
    /**
     * OK
     */
    200: RTenant;
};

export type UpdateTenantSettingsResponse = UpdateTenantSettingsResponses[keyof UpdateTenantSettingsResponses];

export type ListUsersData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: {
        /**
         * 页码（默认1）
         */
        page?: number;
        /**
         * 每页数量（默认10）
         */
        size?: number;
        /**
         * 是否分页，0=返回全部（默认1）
         */
        is_pager?: number;
        /**
         * 关键词搜索
         */
        keyword?: string;
    };
    url: '/v1/tenants/{slug}/users';
};

export type ListUsersResponses = {
    /**
     * OK
     */
    200: RTenantUserList;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type AddUserData = {
    /**
     * 成员信息
     */
    body: {
        email?: string;
        name?: string;
        password?: string;
        role?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
    };
    query?: never;
    url: '/v1/tenants/{slug}/users';
};

export type AddUserResponses = {
    /**
     * OK
     */
    200: R;
};

export type AddUserResponse = AddUserResponses[keyof AddUserResponses];

export type RemoveUserData = {
    body?: never;
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 用户ID
         */
        userId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/users/{userId}';
};

export type RemoveUserResponses = {
    /**
     * OK
     */
    200: R;
};

export type RemoveUserResponse = RemoveUserResponses[keyof RemoveUserResponses];

export type UpdateUserRoleData = {
    /**
     * 角色
     */
    body: {
        role?: string;
    };
    path: {
        /**
         * 租户slug
         */
        slug: string;
        /**
         * 用户ID
         */
        userId: number;
    };
    query?: never;
    url: '/v1/tenants/{slug}/users/{userId}/role';
};

export type UpdateUserRoleResponses = {
    /**
     * OK
     */
    200: R;
};

export type UpdateUserRoleResponse = UpdateUserRoleResponses[keyof UpdateUserRoleResponses];
