// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type RegisterRequest = {
    email: string;
    name: string;
    password: string;
    tenant_name?: string;
    tenant_slug?: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type AuthResponse = {
    user?: User;
    token?: string;
    tenant?: Tenant;
    tenants?: Array<Tenant>;
};

export type User = {
    id?: number;
    email?: string;
    name?: string;
    is_superadmin?: boolean;
    created_at?: string;
    updated_at?: string;
};

export type Tenant = {
    id?: number;
    name?: string;
    slug?: string;
    plan?: 'Free' | 'Pro' | 'Enterprise';
    status?: 'Active' | 'Warning' | 'Suspended';
    created_at?: string;
    updated_at?: string;
};

export type CreateTenantRequest = {
    name: string;
    slug: string;
    plan?: 'Free' | 'Pro' | 'Enterprise';
};

export type UpdateTenantRequest = {
    name?: string;
    plan?: 'Free' | 'Pro' | 'Enterprise';
    status?: 'Active' | 'Warning' | 'Suspended';
};

export type TenantUser = {
    tenant_id?: number;
    user_id?: number;
    role?: 'Admin' | 'Viewer';
    joined_at?: string;
    user?: User;
};

export type AddUserRequest = {
    email: string;
    name: string;
    password: string;
    role: 'Admin' | 'Viewer';
};

export type UpdateRoleRequest = {
    role: 'Admin' | 'Viewer';
};

export type Gateway = {
    id?: number;
    tenant_id?: number;
    name?: string;
    status?: 'online' | 'offline';
    ip?: string;
    last_seen?: string;
    version?: string;
};

export type CreateGatewayRequest = {
    name: string;
};

export type CreateGatewayResponse = {
    id?: number;
    name?: string;
    token?: string;
    status?: string;
    version?: string;
};

export type DataSource = {
    id?: number;
    tenant_id?: number;
    name?: string;
    is_dual?: boolean;
    type?: 'mysql' | 'postgres' | 'sqlserver' | 'starrocks' | 'doris' | 'sqlite';
    envs?: Array<DataSourceEnv>;
    created_at?: string;
};

export type DataSourceEnv = {
    id?: number;
    datasource_id?: number;
    env?: 'dev' | 'prod';
    dsn?: string;
    gateway_id?: number;
};

export type CreateDataSourceRequest = {
    name: string;
    type: 'mysql' | 'postgres' | 'sqlserver' | 'starrocks' | 'doris' | 'sqlite';
    is_dual?: boolean;
    envs: Array<{
        env: 'dev' | 'prod';
        dsn: string;
        gateway_id: number;
    }>;
};

export type UpdateDataSourceRequest = {
    name?: string;
    type?: 'mysql' | 'postgres' | 'sqlserver' | 'starrocks' | 'doris' | 'sqlite';
    is_dual?: boolean;
    envs?: Array<{
        env: 'dev' | 'prod';
        dsn: string;
        gateway_id: number;
    }>;
};

export type Project = {
    id?: number;
    tenant_id?: number;
    name?: string;
    description?: string;
    created_at?: string;
};

export type CreateProjectRequest = {
    name: string;
    description?: string;
};

export type UpdateProjectRequest = {
    name?: string;
    description?: string;
};

export type ApiEndpoint = {
    id: number;
    tenant_id: number;
    project_id: number;
    group_id?: number;
    datasource_id?: number;
    path: string;
    methods: Array<string>;
    summary?: string;
    description?: string;
    sql: string;
    params?: Array<string>;
    param_defs?: Array<ParamDef>;
    pre_script_id?: number;
    post_script_id?: number;
    created_at?: string;
};

export type CreateEndpointRequest = {
    path: string;
    methods: Array<string>;
    sql: string;
    params?: Array<string>;
    param_defs?: Array<ParamDef>;
    datasource_id?: number;
    group_id?: number;
    pre_script_id?: number;
    post_script_id?: number;
};

export type UpdateApiEndpointRequest = {
    path?: string;
    methods?: Array<string>;
    sql?: string;
    summary?: string;
    description?: string;
    params?: Array<string>;
    param_defs?: Array<ParamDef>;
    datasource_id?: number;
    group_id?: number;
    pre_script_id?: number;
    post_script_id?: number;
};

export type ParamDef = {
    name: string;
    type: string;
    required: boolean;
    default?: string;
    desc?: string;
};

export type CreateGroupRequest = {
    name: string;
    description?: string;
};

export type UpdateApiGroupRequest = {
    name?: string;
    description?: string;
};

export type ApiGroup = {
    id: number;
    tenant_id: number;
    project_id: number;
    name: string;
    description?: string;
    created_at: string;
};

export type TestQueryRequest = {
    endpoint_id: number;
    params?: {
        [key: string]: string;
    };
    ignore_scripts?: boolean;
};

export type Script = {
    id: number;
    tenant_id: number;
    name: string;
    type: 'pre' | 'post';
    code: string;
    description?: string;
    created_at?: string;
};

export type CreateScriptRequest = {
    name: string;
    type: 'pre' | 'post';
    code: string;
    description?: string;
};

export type UpdateScriptRequest = {
    name?: string;
    type?: 'pre' | 'post';
    code?: string;
    description?: string;
};

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MyTenantsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/v1/my/tenants';
};

export type MyTenantsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListTenantsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        is_pager?: number;
    };
    url: '/api/v1/tenants';
};

export type ListTenantsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateTenantData = {
    body: CreateTenantRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tenants';
};

export type CreateTenantResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteTenantData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}';
};

export type DeleteTenantResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTenantData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}';
};

export type GetTenantResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateTenantData = {
    body: UpdateTenantRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}';
};

export type UpdateTenantResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListUsersData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/v1/tenants/{slug}/users';
};

export type ListUsersResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type AddUserData = {
    body: AddUserRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/users';
};

export type AddUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateUserRoleData = {
    body: UpdateRoleRequest;
    path: {
        slug: string;
        userId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/users/{userId}/role';
};

export type UpdateUserRoleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RemoveUserData = {
    body?: never;
    path: {
        slug: string;
        userId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/users/{userId}';
};

export type RemoveUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListGatewaysData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/gateways';
};

export type ListGatewaysResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateGatewayData = {
    body: CreateGatewayRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/gateways';
};

export type CreateGatewayResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteGatewayData = {
    body?: never;
    path: {
        slug: string;
        gatewayId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/gateways/{gatewayId}';
};

export type DeleteGatewayResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGatewayData = {
    body?: never;
    path: {
        slug: string;
        gatewayId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/gateways/{gatewayId}';
};

export type GetGatewayResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListDataSourcesData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/datasources';
};

export type ListDataSourcesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateDataSourceData = {
    body: CreateDataSourceRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/datasources';
};

export type CreateDataSourceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteDataSourceData = {
    body?: never;
    path: {
        slug: string;
        datasourceId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type DeleteDataSourceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetDataSourceData = {
    body?: never;
    path: {
        slug: string;
        datasourceId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type GetDataSourceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateDataSourceData = {
    body: UpdateDataSourceRequest;
    path: {
        slug: string;
        datasourceId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/datasources/{datasourceId}';
};

export type UpdateDataSourceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListProjectsData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects';
};

export type ListProjectsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateProjectData = {
    body: CreateProjectRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects';
};

export type CreateProjectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteProjectData = {
    body?: never;
    path: {
        slug: string;
        projectId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}';
};

export type DeleteProjectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProjectData = {
    body?: never;
    path: {
        slug: string;
        projectId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}';
};

export type GetProjectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateProjectData = {
    body: UpdateProjectRequest;
    path: {
        slug: string;
        projectId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}';
};

export type UpdateProjectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListEndpointsData = {
    body?: never;
    path: {
        slug: string;
        projectId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/endpoints';
};

export type ListEndpointsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateEndpointData = {
    body: CreateEndpointRequest;
    path: {
        slug: string;
        projectId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/endpoints';
};

export type CreateEndpointResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteEndpointData = {
    body?: never;
    path: {
        slug: string;
        projectId: number;
        endpointId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}';
};

export type DeleteEndpointResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateEndpointData = {
    body: UpdateApiEndpointRequest;
    path: {
        slug: string;
        projectId: number;
        endpointId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/endpoints/{endpointId}';
};

export type UpdateEndpointResponses = {
    /**
     * OK
     */
    200: ApiEndpoint;
};

export type UpdateEndpointResponse = UpdateEndpointResponses[keyof UpdateEndpointResponses];

export type ListGroupsData = {
    body?: never;
    path: {
        slug: string;
        projectId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/groups';
};

export type ListGroupsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateGroupData = {
    body: CreateGroupRequest;
    path: {
        slug: string;
        projectId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/groups';
};

export type CreateGroupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteGroupData = {
    body?: never;
    path: {
        slug: string;
        projectId: number;
        groupId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/groups/{groupId}';
};

export type DeleteGroupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateGroupData = {
    body: UpdateApiGroupRequest;
    path: {
        slug: string;
        projectId: number;
        groupId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/groups/{groupId}';
};

export type UpdateGroupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ExportOpenApiData = {
    body?: never;
    path: {
        slug: string;
        projectId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/projects/{projectId}/openapi.json';
};

export type ExportOpenApiResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type TestQueryData = {
    body: TestQueryRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/query/test';
};

export type TestQueryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListScriptsData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/scripts';
};

export type ListScriptsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateScriptData = {
    body: CreateScriptRequest;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/scripts';
};

export type CreateScriptResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteScriptData = {
    body?: never;
    path: {
        slug: string;
        scriptId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/scripts/{scriptId}';
};

export type DeleteScriptResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateScriptData = {
    body: UpdateScriptRequest;
    path: {
        slug: string;
        scriptId: number;
    };
    query?: never;
    url: '/api/v1/tenants/{slug}/scripts/{scriptId}';
};

export type UpdateScriptResponses = {
    /**
     * OK
     */
    200: unknown;
};
